export const WEAK_FORMS = [
  { word: "the",    strong: "/ðiː/",      weak: "/ðə/",       tip: "辅音前/ðə/，元音前/ðɪ/" },
  { word: "a / an", strong: "/eɪ/ /æn/", weak: "/ə/ /ən/",   tip: "冠词几乎永远弱读" },
  { word: "of",     strong: "/ɒv/",       weak: "/əv/",       tip: "介词弱读，/f/→/v/ 有声化" },
  { word: "to",     strong: "/tuː/",      weak: "/tə/",       tip: "辅音前/tə/，元音前/tʊ/" },
  { word: "for",    strong: "/fɔː/",      weak: "/fə/",       tip: "介词弱读" },
  { word: "and",    strong: "/ænd/",      weak: "/ən/ /n/",   tip: "口语中常缩为/n/甚至/ŋ/" },
  { word: "but",    strong: "/bʌt/",      weak: "/bət/",      tip: "连词弱读" },
  { word: "that",   strong: "/ðæt/",      weak: "/ðət/",      tip: "作连词或代词时弱读" },
  { word: "can",    strong: "/kæn/",      weak: "/kən/",      tip: "情态动词弱读；否定 can't /kɑːnt/ 不弱读" },
  { word: "have",   strong: "/hæv/",      weak: "/həv/ /əv/", tip: "助动词弱读；实义动词保留强读" },
  { word: "do",     strong: "/duː/",      weak: "/də/",       tip: "助动词弱读" },
  { word: "at",     strong: "/æt/",       weak: "/ət/",       tip: "介词弱读" },
  { word: "are",    strong: "/ɑː/",       weak: "/ə/",        tip: "be动词弱读" },
  { word: "was",    strong: "/wɒz/",      weak: "/wəz/",      tip: "be动词弱读" },
  { word: "from",   strong: "/frɒm/",     weak: "/frəm/",     tip: "介词弱读" },
  { word: "or",     strong: "/ɔː/",       weak: "/ə/",        tip: "连词弱读" },
  { word: "than",   strong: "/ðæn/",      weak: "/ðən/",      tip: "连词弱读" },
  { word: "would",  strong: "/wʊd/",      weak: "/wəd/ /'d/", tip: "情态动词弱读" },
  { word: "could",  strong: "/kʊd/",      weak: "/kəd/",      tip: "情态动词弱读" },
  { word: "should", strong: "/ʃʊd/",      weak: "/ʃəd/",      tip: "情态动词弱读" },
];
