const TEA_PARTY_STORY = {
  title: "The Tea Party",
  paragraphs: [
    "In the 18th century, many people lived in the American colonies.",
    "At that time, they bought tea from Britain.",
    "However, Britain asked them to pay more taxes on tea, so many people thought this was unfair.",
    "One night, two friends were talking near Boston Harbor.",
    "John: Why do we have to pay so much tax?",
    "Mike: Because Britain makes the rules.",
    "John: But we don't think it's fair.",
    "Mike: We must do something.",
    "Later that night, many people went onto the ships and threw the tea into the sea.",
    "As a result, this event became known as the Boston Tea Party.",
    "A few years later, America became an independent country.",
  ],
  notes: [
    {
      title: "词汇笔记",
      items: [
        "colony / colonies：殖民地。American colonies 指美国独立前由英国统治的北美殖民地；复数把 y 变成 ies。",
        "Britain：英国。讲英国历史或美国独立背景时常出现，注意首字母大写。",
        "tax / taxes：税；taxes 是复数。pay taxes 表示“纳税/交税”。",
        "unfair：不公平的，由 un- + fair 构成，un- 常表示否定。",
        "harbor：港口。Boston Harbor 是波士顿港，是故事事件发生地点。",
        "ship：船；went onto the ships 表示“登上船”。",
        "event：事件。this event 指把茶叶倒入海中的历史事件。",
        "independent：独立的。an independent country 表示“一个独立国家”。",
      ],
    },
    {
      title: "短语笔记",
      items: [
        "at that time：在那时，用来交代历史背景。",
        "pay taxes on tea：为茶叶缴税。on 后接被征税的对象。",
        "make the rules：制定规则。Britain makes the rules 表示英国掌握规则制定权。",
        "do something：采取行动。口语中常表示“得做点什么”。",
        "throw ... into ...：把……扔进……。threw the tea into the sea 是过去式表达。",
        "as a result：结果，因此，用于说明后果。",
        "became known as：后来被称为。became 是 become 的过去式。",
        "a few years later：几年后，常用于故事时间推进。",
      ],
    },
    {
      title: "句型笔记",
      items: [
        "Why do we have to ...?：询问“为什么我们必须……？” have to 表示外部要求或不得不做。",
        "Because ...：回答 why 问题时常用 because 引出原因。",
        "We don't think it's fair.：否定前移，中文理解为“我们认为这不公平”。",
        "Britain asked them to pay ...：ask somebody to do something 表示“要求某人做某事”。",
        "so many people thought this was unfair：so 连接原因和结果，表示“所以”。",
        "this event became known as ...：被动意义的固定表达，表示“这一事件被称为……”。",
      ],
    },
    {
      title: "语法笔记",
      items: [
        "一般过去时贯穿全文：lived、bought、asked、thought、went、threw、became 用来讲历史事件。",
        "过去进行时：two friends were talking 表示当时“正在谈话”的背景动作。",
        "宾语从句：many people thought this was unfair 中 this was unfair 是 thought 的内容。",
        "there is/are 的历史叙述替代表达：many people lived in ... 直接交代人物和地点，比逐词翻译更自然。",
        "代词指代：them 指 American colonies 的 people；this event 指倒茶入海这件事。",
      ],
    },
    {
      title: "朗读提示",
      items: [
        "历史背景句平稳降调：In the 18th century / many people lived in the American colonies. 先在时间短语后停顿。",
        "转折词 However 要读清，后面 Britain asked them to pay more taxes on tea 是核心信息，taxes、tea 可重读。",
        "对话句要有情绪：Why do we have to pay so much tax? 用疑问语气，Why 开头的特殊疑问句整体降调。",
        "连读：thought this、went onto、became known as 可自然连读，不要逐词断开。",
        "结尾句 America became an independent country. 用稳定降调，independent country 是重点。",
      ],
    },
  ],
};

const DAY_7_STORIES = [
  {
    title: "The Sword in the Stone",
    paragraphs: [
      "Long ago, England did not have a king, so the people wanted to find the right person to rule the country.",
      "One day, they found a strange sword in a big stone. There were some words on the stone: \"Only the true king can pull out this sword.\"",
      "After that, many strong men tried to pull out the sword, but no one could do it.",
      "Then, a young boy named Arthur walked to the stone. He was kind and honest. Although he was not strong, he held the sword with both hands.",
      "Slowly, the sword came out!",
      "Everyone was surprised.",
      "Man: You did it!",
      "Arthur: I don't understand. I'm only a boy.",
      "Old Man: You are brave and kind. That is why you are the true king.",
      "From that day on, Arthur became the King of England, and people remembered him as a wise and brave king.",
    ],
    notes: [
      {
        title: "词汇笔记",
        items: [
          "sword：剑。w 不发音，读音接近 /sɔːd/。",
          "stone：石头。the sword in the stone 是故事核心意象。",
          "rule：统治；管理。rule the country 表示“治理国家”。",
          "true：真正的。the true king 指真正有资格成为国王的人。",
          "pull out：拔出。pull out this sword 是重点动作。",
          "Arthur：亚瑟。人名首字母大写。",
          "honest：诚实的。h 不发音，读音以元音开头。",
          "brave：勇敢的；wise：明智的。两个词用于评价人物品质。",
        ],
      },
      {
        title: "短语笔记",
        items: [
          "long ago：很久以前，常用于故事开头。",
          "the right person：合适的人。",
          "try to do something：努力尝试做某事。",
          "with both hands：用双手。",
          "from that day on：从那天起。",
          "be remembered as：被铭记为。",
        ],
      },
      {
        title: "句型笔记",
        items: [
          "There were some words on the stone：there be 句型表示“某处有……”。",
          "Only the true king can pull out this sword.：only 放句首强调“只有……”。",
          "Although he was not strong, he held the sword with both hands.：although 引导让步，中文是“虽然……但是……”，英文中不再加 but。",
          "That is why you are the true king.：That is why ... 表示“这就是为什么……”。",
        ],
      },
      {
        title: "语法笔记",
        items: [
          "一般过去时叙事：wanted、found、tried、walked、held、came、became、remembered。",
          "情态动词 can/could：can pull out 表示能力；could do it 用于过去能力或可能性。",
          "形容词并列：kind and honest、wise and brave 用 and 连接两个品质。",
          "named Arthur 是过去分词短语作后置定语，说明“一个名叫 Arthur 的男孩”。",
        ],
      },
      {
        title: "朗读提示",
        items: [
          "故事开头 Long ago 后轻停顿，England、king、right person、rule the country 重读。",
          "引号句 Only the true king can pull out this sword. 要读得庄重，true king 和 this sword 重读。",
          "Slowly, the sword came out! 可放慢节奏，Slowly 后停顿，句尾带惊喜感。",
          "对话分角色朗读：Man 激动，Arthur 困惑，Old Man 稳定肯定。",
        ],
      },
    ],
  },
  {
    title: "The Boy Who Became a President",
    paragraphs: [
      "Abraham Lincoln was born into a poor family in America.",
      "When he was a child, he lived in a small wooden house.",
      "Although his family did not have much money, Lincoln loved reading very much.",
      "He borrowed books from other people and studied whenever he had time.",
      "As he grew older, he worked hard and became a lawyer.",
      "Later, he became the President of the United States.",
      "During his presidency, America faced a terrible war between the North and the South.",
      "Lincoln believed that slavery was wrong and that people should be free.",
      "Therefore, he worked to bring freedom to millions of enslaved people.",
      "During the war, Lincoln gave one of the most famous speeches in American history.",
      "He spoke of \"government of the people, by the people, for the people.\"",
      "Today, people around the world remember Lincoln as one of America's most important leaders.",
    ],
    notes: [
      {
        title: "词汇笔记",
        items: [
          "president：总统。the President of the United States 指美国总统。",
          "wooden：木制的。a small wooden house 表示“一座小木屋”。",
          "borrow：借入。borrow books from other people 是“向别人借书”。",
          "lawyer：律师。Lincoln became a lawyer 表示职业变化。",
          "presidency：总统任期；总统职位。",
          "slavery：奴隶制。believed that slavery was wrong 是人物信念核心。",
          "freedom：自由。bring freedom to ... 表示“给……带来自由”。",
          "enslaved：被奴役的。enslaved people 指被奴役的人。",
          "speech / speeches：演讲；speeches 是复数。",
        ],
      },
      {
        title: "短语笔记",
        items: [
          "be born into：出生在……家庭。",
          "whenever he had time：只要他有时间。",
          "as he grew older：随着他长大。",
          "work hard：努力工作/学习。",
          "between the North and the South：在北方和南方之间。",
          "millions of：数百万的。",
          "around the world：全世界。",
          "one of America's most important leaders：美国最重要的领导人之一。",
        ],
      },
      {
        title: "句型笔记",
        items: [
          "When he was a child, he lived ...：when 引导时间状语从句，先交代时间再讲事件。",
          "Although his family did not have much money, Lincoln loved reading very much.：although 表让步，强调条件困难但仍热爱阅读。",
          "Lincoln believed that slavery was wrong and that people should be free.：两个 that 从句并列，都是 believed 的内容。",
          "He spoke of \"government of the people, by the people, for the people.\"：三个 of/by/for 形成排比，朗读时节奏要整齐。",
        ],
      },
      {
        title: "语法笔记",
        items: [
          "过去式与人物传记：was born、lived、borrowed、studied、became、faced、believed、worked、gave、spoke。",
          "whenever 引导时间状语从句，含义是“无论什么时候/只要”。",
          "should be free 中 should 表示价值判断或应该如此。",
          "one of + 最高级 + 名词复数：one of America's most important leaders，leaders 要用复数。",
          "介词 during 表示“在……期间”，during his presidency、during the war 都是时间背景。",
        ],
      },
      {
        title: "朗读提示",
        items: [
          "传记类朗读要稳：Abraham Lincoln、poor family、small wooden house 是背景重点。",
          "Although 句先让步后转核心，Lincoln loved reading very much 要读出强调。",
          "slavery、wrong、free、freedom 是价值关键词，需要清楚重读。",
          "government of the people, by the people, for the people 三段排比每段之间轻停顿，最后降调收束。",
        ],
      },
    ],
  },
  {
    title: "The General Who Dreamed of an Empire",
    paragraphs: [
      "More than two hundred years ago, a young man named Napoleon Bonaparte lived in France.",
      "He was very good at leading an army, so he soon became a famous general.",
      "At that time, France was fighting against many countries in Europe, including Britain.",
      "Napoleon won many battles, and later, he became the leader of France.",
      "He wanted to build a strong and powerful country.",
      "However, Britain was one of his strongest enemies.",
      "In 1805, the British navy won an important battle against France at sea.",
      "As a result, Napoleon could not defeat Britain.",
      "Years later, Napoleon lost power, but he returned to France and became the leader again.",
      "However, in 1815, he lost the famous Battle of Waterloo.",
      "After that, his time as a leader finally came to an end.",
      "Although Napoleon lost in the end, he changed European history and is one of the most famous people in history today.",
    ],
    notes: [
      {
        title: "词汇笔记",
        items: [
          "general：将军。a famous general 指著名将领。",
          "empire：帝国。dreamed of an empire 表示“梦想建立帝国”。",
          "army：陆军；军队。lead an army 表示“带领军队”。",
          "battle：战役；战斗。won many battles 表示赢得许多战役。",
          "enemy / enemies：敌人；enemies 是复数。",
          "navy：海军。the British navy 指英国海军。",
          "defeat：打败。could not defeat Britain 表示未能击败英国。",
          "Waterloo：滑铁卢。the Battle of Waterloo 是拿破仑失败的关键战役。",
        ],
      },
      {
        title: "短语笔记",
        items: [
          "more than two hundred years ago：两百多年前。",
          "be good at doing：擅长做某事。be good at leading an army 表示擅长带兵。",
          "fight against：与……作战。",
          "including Britain：包括英国在内。",
          "at sea：在海上。",
          "lose power：失去权力。",
          "come to an end：结束。",
          "in the end：最后，最终。",
        ],
      },
      {
        title: "句型笔记",
        items: [
          "He was very good at leading an army, so he soon became a famous general.：so 连接结果。",
          "Britain was one of his strongest enemies.：one of + 形容词最高级 + 名词复数。",
          "As a result, Napoleon could not defeat Britain.：as a result 放句首，引出结果。",
          "Although Napoleon lost in the end, he changed European history ...：although 表让步，重点落在 he changed European history。",
        ],
      },
      {
        title: "语法笔记",
        items: [
          "过去进行时：France was fighting against many countries 表示当时持续的战争状态。",
          "情态动词 could not：表示过去未能做到。",
          "序数与年份朗读：1805 可读 eighteen oh five；1815 可读 eighteen fifteen。",
          "比较与最高级：strong and powerful 是并列形容词；strongest 是最高级。",
          "named Napoleon Bonaparte 是后置定语，说明人物姓名。",
        ],
      },
      {
        title: "朗读提示",
        items: [
          "Napoleon Bonaparte 是长人名，可分成 Napoleon / Bonaparte 两个意群练习。",
          "However 出现两次，都提示转折，朗读时前后语气要有变化。",
          "In 1805 和 in 1815 是时间锚点，后面各停顿一次。",
          "Battle of Waterloo 是专名，Battle、Waterloo 重读，结尾句用总结性降调。",
        ],
      },
    ],
  },
  {
    title: "From Britain to America",
    paragraphs: [
      "Hundreds of years ago, Britain became one of the most powerful countries in the world.",
      "Many English people traveled across the Atlantic Ocean and built new communities in North America.",
      "At first, the American colonies were connected to Britain.",
      "People spoke English, followed British laws, and shared many traditions.",
      "However, over time, problems appeared.",
      "The colonies disagreed with Britain about taxes and political rights.",
      "Many people believed that they should have the power to make their own decisions.",
      "In 1776, the American colonies declared independence.",
      "After a long war, the United States became a new country.",
      "Although Britain and America once fought against each other, they continued to share the English language and many cultural traditions.",
      "Today, British English and American English are two important varieties of the English language.",
    ],
    notes: [
      {
        title: "词汇笔记",
        items: [
          "powerful：强大的。one of the most powerful countries 表示最强大的国家之一。",
          "Atlantic Ocean：大西洋。专有名词首字母大写。",
          "community / communities：社区；定居点。built new communities 指建立新的居住群体。",
          "law：法律。British laws 指英国法律。",
          "tradition：传统。shared many traditions 表示共享许多传统。",
          "political：政治的。political rights 指政治权利。",
          "declare：宣布。declared independence 表示宣布独立。",
          "variety / varieties：变体；种类。British English and American English are two varieties。",
        ],
      },
      {
        title: "短语笔记",
        items: [
          "hundreds of years ago：几百年前。",
          "travel across：横跨；穿越。",
          "be connected to：与……相连。",
          "at first：起初。",
          "over time：随着时间推移。",
          "disagree with somebody about something：在某事上与某人意见不一致。",
          "make their own decisions：做出自己的决定。",
          "fight against each other：互相作战。",
        ],
      },
      {
        title: "句型笔记",
        items: [
          "Britain became one of the most powerful countries in the world.：one of + 最高级 + 名词复数。",
          "People spoke English, followed British laws, and shared many traditions.：三个并列谓语 spoke、followed、shared，朗读时形成并列节奏。",
          "Many people believed that they should have the power to make their own decisions.：that 从句作 believed 的宾语；to make their own decisions 修饰 power。",
          "Although Britain and America once fought against each other, they continued to share ...：although 引导让步，continued to share 是重点结果。",
        ],
      },
      {
        title: "语法笔记",
        items: [
          "一般过去时讲历史发展：became、traveled、built、spoke、followed、shared、appeared、disagreed、declared。",
          "被动语态：were connected to Britain 表示殖民地和英国之间的关系。",
          "情态意义 should have：should 表示“应该拥有”。",
          "continued to do：继续做某事，后接不定式。",
          "British English / American English 是专有概念，English 首字母大写。",
        ],
      },
      {
        title: "朗读提示",
        items: [
          "Hundreds of years ago 后停顿，Britain、powerful countries、world 重读。",
          "traveled across the Atlantic Ocean 可按 traveled across / the Atlantic Ocean 分意群。",
          "spoke English, followed British laws, and shared many traditions 是三连并列，逗号处轻停顿。",
          "However, over time, problems appeared. 句子短但转折明显，However 与 problems appeared 要读清。",
          "British English and American English 是对比信息，两个专名都要清晰重读。",
        ],
      },
    ],
  },
];

// 保留为模块内部数据源，供 Day5 阅读评估面板后续引用；
// 下划线前缀标示"当前未在页面中消费"，由 eslint no-unused-vars 放行。
const _DAY_5_READING_ASSESSMENTS = [
  {
    id: "camp-d5-read-linking",
    title: "连读专项朗读",
    prompt: "Pick it up and stand up.",
    focus: ["pick‿it", "it‿up", "stand‿up"],
  },
  {
    id: "camp-d5-read-plosive",
    title: "失去爆破专项朗读",
    prompt: "The good boy sat down with a black cat.",
    focus: ["good̚ boy", "sat̚ down", "black̚ cat"],
  },
  {
    id: "camp-d5-read-assimilation",
    title: "同化专项朗读",
    prompt: "Did you see her, and would you help me?",
    focus: ["did you → /dɪdʒə/", "would you → /wʊdʒə/"],
  },
  {
    id: "camp-d5-read-reduction",
    title: "约化与弱化专项朗读",
    prompt: "I want to go to the next day of training.",
    focus: ["want to 可约化", "to 弱读", "next day 中 /t/ 可弱化"],
  },
];

export const PHONETIC_CAMP_DIRECTORY = [
  { id: "day-1", number: "01", label: "Day 1", title: "解锁元音小家", page: "01" },
  { id: "day-2", number: "02", label: "Day 2", title: "攻克辅音怪兽", page: "11" },
  { id: "day-3", number: "03", label: "Day 3", title: "音节拼词魔法", page: "25" },
  { id: "day-4", number: "04", label: "Day 4", title: "掌握句子韵律", page: "37" },
  { id: "day-5", number: "05", label: "Day 5", title: "破解语流密码", page: "48" },
  { id: "day-6", number: "06", label: "Day 6", title: "走进英语故事", page: "64" },
  { id: "day-7", number: "07", label: "Day 7", title: "成为朗读达人", page: "69" },
  { id: "supplement", number: "08", label: "补充练", title: "拓展英语故事练习", page: "72" },
  { id: "appendix", number: "09", label: "附录", title: "常见字母组合的发音", page: "81" },
];

function buildCircleSelectItems(group, sounds, targets) {
  return sounds.map((prompt, index) => ({
    id: `${group}-${index}-${prompt}`,
    group,
    prompt,
    answer: targets.includes(prompt) ? "圈出" : "不圈",
  }));
}

const DAY_1_EXERCISES = [
  {
    id: "day1-listening-radar",
    title: "第一关 听力雷达",
    instruction: "请听录音，在两个音素中圈出你所听到的元音音素，每个音素将播放三遍。",
    type: "choice",
    items: [
      { prompt: "①", options: ["/iː/", "/ɪ/"], answer: "/iː/" },
      { prompt: "②", options: ["/uː/", "/ʊ/"], answer: "/uː/" },
      { prompt: "③", options: ["/e/", "/æ/"], answer: "/æ/" },
      { prompt: "④", options: ["/ɔː/", "/ɒ/"], answer: "/ɔː/" },
      { prompt: "⑤", options: ["/əʊ/", "/aʊ/"], answer: "/aʊ/" },
      { prompt: "⑥", options: ["/eɪ/", "/aɪ/"], answer: "/aɪ/" },
      { prompt: "⑦", options: ["/ɔɪ/", "/eə/"], answer: "/ɔɪ/" },
      { prompt: "⑧", options: ["/ɪə/", "/ʊə/"], answer: "/ɪə/" },
    ],
    answerNote: "参考答案来自用户提供的 Day 1 习题参考答案；提交全部关卡后统一显示。",
  },
  {
    id: "day1-reading",
    title: "第二关 朗读小喇叭",
    instruction: "请跟随录音大声朗读下面的音标和单词。",
    type: "readTable",
    items: [
      { sound: "/iː/", word: "see" },
      { sound: "/ɪ/", word: "sit" },
      { sound: "/e/", word: "pen" },
      { sound: "/æ/", word: "cat" },
      { sound: "/ɑː/", word: "car" },
      { sound: "/ʌ/", word: "cup" },
      { sound: "/ɔː/", word: "ball" },
      { sound: "/ɒ/", word: "dog" },
      { sound: "/ʊ/", word: "book" },
      { sound: "/uː/", word: "food" },
      { sound: "/ɜː/", word: "bird" },
      { sound: "/ə/", word: "about" },
      { sound: "/aɪ/", word: "bike" },
      { sound: "/ɔɪ/", word: "boy" },
      { sound: "/eɪ/", word: "skate" },
      { sound: "/əʊ/", word: "home" },
      { sound: "/aʊ/", word: "house" },
      { sound: "/ɪə/", word: "ear" },
      { sound: "/eə/", word: "bear" },
      { sound: "/ʊə/", word: "tour" },
    ],
  },
  {
    id: "day1-circle-detective",
    title: "第三关 圈音侦探",
    instruction: "按每小题要求，点击圈出对应类型的元音。",
    type: "circleSelect",
    items: [
      ...buildCircleSelectItems(
        "① 圈出所有长元音",
        ["/iː/", "/ɪ/", "/e/", "/æ/", "/ɑː/", "/ʌ/", "/ɔː/", "/ɒ/", "/ʊ/", "/uː/", "/ɜː/", "/ə/"],
        ["/iː/", "/ɑː/", "/ɔː/", "/uː/", "/ɜː/"],
      ),
      ...buildCircleSelectItems(
        "② 圈出所有双元音",
        ["/eɪ/", "/aɪ/", "/ɔɪ/", "/əʊ/", "/aʊ/", "/ɪə/", "/eə/", "/ʊə/", "/iː/", "/æ/", "/ʌ/"],
        ["/eɪ/", "/aɪ/", "/ɔɪ/", "/əʊ/", "/aʊ/", "/ɪə/", "/eə/", "/ʊə/"],
      ),
      ...buildCircleSelectItems(
        "③ 圈出所有短元音",
        ["/e/", "/eɪ/", "/ɒ/", "/ɪ/", "/ɑː/", "/ʊ/", "/aɪ/", "/ɜː/", "/æ/", "/ə/", "/ɔː/", "/ʌ/", "/uː/", "/aʊ/", "/ɔɪ/"],
        ["/e/", "/ɒ/", "/ɪ/", "/ʊ/", "/æ/", "/ə/", "/ʌ/"],
      ),
    ],
  },
  {
    id: "day1-family",
    title: "第四关 分类工程师",
    instruction: "请根据元音字母 a、e、i、o、u 把下面的元音音标填写到对应的类别里。",
    type: "classify",
    options: ["A 家族", "E 家族", "I 家族", "O 家族", "U 家族", "中央元音", "双元音剩余"],
    items: [
      ...["/æ/", "/ɑː/", "/eɪ/"].map((prompt) => ({ prompt, answer: "A 家族" })),
      ...["/iː/", "/e/"].map((prompt) => ({ prompt, answer: "E 家族" })),
      ...["/ɪ/", "/aɪ/"].map((prompt) => ({ prompt, answer: "I 家族" })),
      ...["/ɒ/", "/ɔː/", "/ɔɪ/", "/əʊ/", "/aʊ/"].map((prompt) => ({ prompt, answer: "O 家族" })),
      ...["/ʌ/", "/ʊ/", "/uː/"].map((prompt) => ({ prompt, answer: "U 家族" })),
      ...["/ɜː/", "/ə/"].map((prompt) => ({ prompt, answer: "中央元音" })),
      ...["/ɪə/", "/eə/", "/ʊə/"].map((prompt) => ({ prompt, answer: "双元音剩余" })),
    ],
  },
  {
    id: "day1-match",
    title: "第五关 音标连连看",
    instruction: "请将左边的音标与右边含有该发音的单词连线。",
    type: "matchSelect",
    options: ["bear", "house", "bike", "cat", "home", "see", "boy", "bird", "dog", "food", "book", "pen", "car", "cup", "ball", "sit"],
    items: [
      { prompt: "/iː/", answer: "see" },
      { prompt: "/æ/", answer: "cat" },
      { prompt: "/ɜː/", answer: "bird" },
      { prompt: "/əʊ/", answer: "home" },
      { prompt: "/aɪ/", answer: "bike" },
      { prompt: "/ɔɪ/", answer: "boy" },
      { prompt: "/eə/", answer: "bear" },
      { prompt: "/aʊ/", answer: "house" },
      { prompt: "/ɪ/", answer: "sit" },
      { prompt: "/e/", answer: "pen" },
      { prompt: "/ɑː/", answer: "car" },
      { prompt: "/ʌ/", answer: "cup" },
      { prompt: "/ɔː/", answer: "ball" },
      { prompt: "/ɒ/", answer: "dog" },
      { prompt: "/ʊ/", answer: "book" },
      { prompt: "/uː/", answer: "food" },
    ],
  },
];

const DAY_2_EXERCISES = [
  {
    id: "day2-listening-radar",
    title: "第一关 听力雷达",
    instruction: "认真听音频，在下面的音标中圈出你听到的辅音。",
    type: "choice",
    items: [
      { prompt: "①", options: ["/p/", "/t/", "/k/"], answer: "/t/" },
      { prompt: "②", options: ["/w/", "/v/", "/f/"], answer: "/v/" },
      { prompt: "③", options: ["/s/", "/θ/", "/ʃ/"], answer: "/θ/" },
      { prompt: "④", options: ["/ð/", "/z/", "/ʒ/"], answer: "/ð/" },
      { prompt: "⑤", options: ["/tʃ/", "/tr/", "/ts/"], answer: "/tʃ/" },
      { prompt: "⑥", options: ["/dʒ/", "/dr/", "/j/"], answer: "/dʒ/" },
      { prompt: "⑦", options: ["/dz/", "/z/", "/r/"], answer: "/dz/" },
      { prompt: "⑧", options: ["/n/", "/g/", "/ŋ/"], answer: "/ŋ/" },
    ],
    answerNote: "参考答案来自本地 Day 2 听力文本；提交全部关卡后统一显示。",
  },
  {
    id: "day2-reading",
    title: "第二关 朗读小喇叭",
    instruction: "请大声朗读下面的音标和单词。",
    type: "readTable",
    items: [
      { sound: "/p/", word: "pen / happy / cup" },
      { sound: "/t/", word: "tea / potato / cat" },
      { sound: "/k/", word: "car / monkey / book" },
      { sound: "/m/", word: "moon / summer / ham" },
      { sound: "/n/", word: "nose / banana / pen" },
      { sound: "/l/", word: "leg / yellow / ball" },
      { sound: "/r/", word: "red / carrot / car" },
      { sound: "/f/", word: "fish" },
      { sound: "/v/", word: "van" },
      { sound: "/w/", word: "window" },
      { sound: "/θ/", word: "think" },
      { sound: "/s/", word: "sun" },
      { sound: "/ð/", word: "this" },
      { sound: "/z/", word: "zoo" },
      { sound: "/ʃ/", word: "she" },
      { sound: "/ʒ/", word: "television" },
      { sound: "/tʃ/", word: "chair" },
      { sound: "/dʒ/", word: "juice" },
      { sound: "/ts/", word: "cats" },
      { sound: "/dz/", word: "birds" },
      { sound: "/tr/", word: "tree" },
      { sound: "/dr/", word: "dress" },
      { sound: "/ŋ/", word: "sing" },
      { sound: "/h/", word: "hair" },
      { sound: "/j/", word: "yellow" },
    ],
  },
  {
    id: "day2-circle-detective",
    title: "第三关 圈音侦探",
    instruction: "按每小题要求，点击圈出对应类型的辅音。",
    type: "circleSelect",
    items: [
      ...buildCircleSelectItems(
        "① 圈出所有清辅音",
        ["/p/", "/b/", "/t/", "/d/", "/k/", "/g/", "/f/", "/v/", "/θ/", "/ð/", "/s/", "/z/", "/ʃ/", "/ʒ/", "/tʃ/", "/dʒ/"],
        ["/p/", "/t/", "/k/", "/f/", "/θ/", "/s/", "/ʃ/", "/tʃ/"],
      ),
      ...buildCircleSelectItems(
        "② 圈出所有浊辅音",
        ["/p/", "/b/", "/t/", "/d/", "/k/", "/g/", "/f/", "/v/", "/θ/", "/ð/", "/s/", "/z/", "/ʃ/", "/ʒ/", "/tʃ/", "/dʒ/"],
        ["/b/", "/d/", "/g/", "/v/", "/ð/", "/z/", "/ʒ/", "/dʒ/"],
      ),
      ...buildCircleSelectItems(
        "③ 圈出所有鼻音和半元音",
        ["/m/", "/t/", "/n/", "/l/", "/ŋ/", "/r/", "/j/", "/w/", "/b/", "/s/"],
        ["/m/", "/n/", "/ŋ/", "/j/", "/w/"],
      ),
    ],
  },
  {
    id: "day2-category",
    title: "第四关 分类工程师",
    instruction: "请根据分类方式把辅音音标填写到对应的类别里。",
    type: "classify",
    options: ["爆破音", "摩擦音", "破擦音", "辅音连缀", "鼻音", "流音", "半元音", "声门音"],
    items: [
      ...["/p/", "/b/", "/t/", "/d/", "/k/", "/g/"].map((prompt) => ({ prompt, answer: "爆破音" })),
      ...["/f/", "/v/", "/θ/", "/ð/", "/s/", "/z/", "/ʃ/", "/ʒ/"].map((prompt) => ({ prompt, answer: "摩擦音" })),
      ...["/tʃ/", "/dʒ/"].map((prompt) => ({ prompt, answer: "破擦音" })),
      ...["/tr/", "/dr/", "/ts/", "/dz/"].map((prompt) => ({ prompt, answer: "辅音连缀" })),
      ...["/m/", "/n/", "/ŋ/"].map((prompt) => ({ prompt, answer: "鼻音" })),
      ...["/l/", "/r/"].map((prompt) => ({ prompt, answer: "流音" })),
      ...["/j/", "/w/"].map((prompt) => ({ prompt, answer: "半元音" })),
      { prompt: "/h/", answer: "声门音" },
    ],
  },
  {
    id: "day2-match",
    title: "第五关 音标连连看",
    instruction: "请将左边的音标与右边含有该发音的单词连线。",
    type: "matchSelect",
    options: ["carrot", "happy", "moon", "bag", "potato", "rabbit", "monkey", "dog", "yellow", "red", "chair", "yes", "zoo", "fish", "we", "this", "van", "think", "television", "she", "juice"],
    items: [
      { prompt: "/b/", answer: "rabbit" },
      { prompt: "/p/", answer: "happy" },
      { prompt: "/t/", answer: "potato" },
      { prompt: "/d/", answer: "dog" },
      { prompt: "/k/", answer: "carrot" },
      { prompt: "/g/", answer: "bag" },
      { prompt: "/m/", answer: "monkey" },
      { prompt: "/n/", answer: "moon" },
      { prompt: "/l/", answer: "yellow" },
      { prompt: "/r/", answer: "red" },
      { prompt: "/f/", answer: "fish" },
      { prompt: "/v/", answer: "van" },
      { prompt: "/θ/", answer: "think" },
      { prompt: "/ð/", answer: "this" },
      { prompt: "/s/", answer: "yes" },
      { prompt: "/z/", answer: "zoo" },
      { prompt: "/ʃ/", answer: "she" },
      { prompt: "/ʒ/", answer: "television" },
      { prompt: "/tʃ/", answer: "chair" },
      { prompt: "/dʒ/", answer: "juice" },
    ],
  },
];

const DAY_3_EXERCISES = [
  {
    id: "day3-syllable-count",
    title: "第一关 音节小侦探",
    instruction: "请先用 / 划分下面单词的音节，再数出它们一共有几个音节。",
    type: "textPairs",
    fields: ["划分音节", "音节数"],
    items: [
      { prompt: "important", answer: "im/por/tant；3" },
      { prompt: "holiday", answer: "ho/li/day；3" },
      { prompt: "happy", answer: "hap/py；2" },
      { prompt: "cat", answer: "cat；1" },
      { prompt: "book", answer: "book；1" },
      { prompt: "basketball", answer: "bas/ket/ball；3" },
      { prompt: "computer", answer: "com/pu/ter；3" },
      { prompt: "wonderful", answer: "won/der/ful；3" },
      { prompt: "banana", answer: "ba/na/na；3" },
      { prompt: "pencil", answer: "pen/cil；2" },
      { prompt: "orange", answer: "or/ange；2" },
      { prompt: "university", answer: "u/ni/ver/si/ty；5" },
      { prompt: "information", answer: "in/for/ma/tion；4" },
      { prompt: "elephant", answer: "e/le/phant；3" },
      { prompt: "teacher", answer: "tea/cher；2" },
      { prompt: "hospital", answer: "hos/pi/tal；3" },
    ],
  },
  {
    id: "day3-stress",
    title: "第二关 重音工程师",
    instruction: "请先用 / 划分下面单词的音节，并在重读音节下标记 ●。",
    type: "text",
    items: [
      { prompt: "apple", answer: "●ap/ple" },
      { prompt: "museum", answer: "mu/●seum" },
      { prompt: "together", answer: "to/●ge/ther" },
      { prompt: "tomorrow", answer: "to/●mor/row" },
      { prompt: "exciting", answer: "ex/●ci/ting" },
      { prompt: "camera", answer: "●ca/me/ra" },
      { prompt: "beautiful", answer: "●beau/ti/ful" },
      { prompt: "potato", answer: "po/●ta/to" },
      { prompt: "America", answer: "A/●me/ri/ca" },
      { prompt: "doctor", answer: "●doc/tor" },
      { prompt: "interesting", answer: "●in/teres/ting" },
      { prompt: "remember", answer: "re/●mem/ber" },
      { prompt: "about", answer: "a/●bout" },
      { prompt: "enjoy", answer: "en/●joy" },
      { prompt: "internet", answer: "●in/ter/net" },
      { prompt: "difficult", answer: "●dif/fi/cult" },
      { prompt: "chocolate", answer: "●choc/late" },
      { prompt: "delicious", answer: "de/●li/cious" },
    ],
  },
  {
    id: "day3-open-closed",
    title: "第三关 规律发现师",
    instruction: "请判断开/闭音节，并写出元音音标。",
    type: "textPairs",
    fields: ["开/闭音节", "元音音标"],
    items: [
      { prompt: "tiger", answer: "开音节；/aɪ/" },
      { prompt: "paper", answer: "开音节；/eɪ/" },
      { prompt: "hotel", answer: "闭音节；/e/" },
      { prompt: "basic", answer: "开音节；/eɪ/" },
      { prompt: "music", answer: "开音节；/juː/" },
      { prompt: "lady", answer: "开音节；/eɪ/" },
      { prompt: "picnic", answer: "闭音节；/ɪ/" },
      { prompt: "window", answer: "开音节；/əʊ/" },
      { prompt: "wonderful", answer: "闭音节；/ə/" },
      { prompt: "tomato", answer: "开音节；/eɪ/" },
      { prompt: "computer", answer: "开音节；/juː/" },
      { prompt: "potato", answer: "开音节；/eɪ/" },
      { prompt: "elephant", answer: "开音节；/e/" },
      { prompt: "invite", answer: "闭音节；/ɪ/" },
      { prompt: "robot", answer: "闭音节；/ɒ/ 或 /ɑː/" },
      { prompt: "student", answer: "开音节；/juː/" },
    ],
    answerNote: "开音节里元音字母常读字母音；闭音节里元音字母通常读短元音。多音节词要以目标音节和音标核对。",
  },
  {
    id: "day3-pronunciation",
    title: "第四关 发音小达人",
    instruction: "请根据划线部分的发音规律，为单词的正确读音打勾。",
    type: "choice",
    items: [
      { prompt: "children", options: ["A. /tʃaɪl/", "B. /tʃɪl/", "C. /tʃiːl/"], answer: "B. /tʃɪl/" },
      { prompt: "winter", options: ["A. /wɪn/", "B. /waɪn/", "C. /wiːn/"], answer: "A. /wɪn/" },
      { prompt: "happen", options: ["A. /pən/", "B. /pen/", "C. /piːn/"], answer: "A. /pən/" },
      { prompt: "lesson", options: ["A. /liːs/", "B. /les/", "C. /leɪs/"], answer: "B. /les/" },
      { prompt: "animal", options: ["A. /ɑːn/", "B. /eɪn/", "C. /æn/"], answer: "C. /æn/" },
      { prompt: "doctor", options: ["A. /dɒk/", "B. /dəʊk/", "C. /diːk/"], answer: "A. /dɒk/" },
      { prompt: "begin", options: ["A. /ɡɪn/", "B. /ɡaɪn/", "C. /ɡiːn/"], answer: "A. /ɡɪn/" },
      { prompt: "dinner", options: ["A. /daɪn/", "B. /dɪn/", "C. /diːn/"], answer: "B. /dɪn/" },
      { prompt: "rabbit", options: ["A. /reɪb/", "B. /ræb/", "C. /rɑːb/"], answer: "B. /ræb/" },
      { prompt: "summer", options: ["A. /sjuːm/", "B. /suːm/", "C. /sʌm/"], answer: "C. /sʌm/" },
      { prompt: "problem", options: ["A. /prɒb/", "B. /prəʊb/", "C. /priːb/"], answer: "A. /prɒb/" },
      { prompt: "market", options: ["A. /mæ/", "B. /meɪ/", "C. /mɑː/"], answer: "C. /mɑː/" },
    ],
  },
];

const DAY_4_EXERCISES = [
  {
    id: "day4-stress",
    title: "第一关 听力雷达",
    instruction: "请听录音，在需要重读的单词下面画 ●，需要弱读的单词下画 ◯，并每句话跟读三遍。",
    type: "sentenceMark",
    markOptions: ["● 重读", "◯ 弱读"],
    items: [
      { prompt: "I like playing football after school.", answer: "◯ I / after；● like / playing / football / school。" },
      { prompt: "My mother cooks dinner every evening.", answer: "◯ My / every；● mother / cooks / dinner / evening。" },
      { prompt: "We visited the zoo last Sunday.", answer: "◯ We / the / last；● visited / zoo / Sunday。" },
      { prompt: "She reads English books every day.", answer: "◯ She / every；● reads / English / books / day。" },
      { prompt: "They went to the park yesterday.", answer: "◯ They / to / the；● went / park / yesterday。" },
      { prompt: "My brother can play the piano.", answer: "◯ My / can / the；● brother / play / piano。" },
      { prompt: "We have an English class this morning.", answer: "◯ We / an / this；● have / English / class / morning。" },
      { prompt: "I want to learn English well.", answer: "◯ I / to；● want / learn / English / well。" },
    ],
    answerNote: "参考原则：名词、实义动词、形容词、副词、时间/地点核心信息多重读；代词、冠词、介词、助动词等功能词多弱读。",
  },
  {
    id: "day4-sense-groups",
    title: "第二关 节奏工程师",
    instruction: "请听录音，用 / 划分停顿（意群），并每句话跟读三遍。",
    type: "sentenceMark",
    markOptions: ["/ 停顿"],
    items: [
      { prompt: "When I got home I finished my homework.", answer: "When I got home / I finished my homework." },
      { prompt: "After dinner we went for a walk.", answer: "After dinner / we went for a walk." },
      { prompt: "If it rains tomorrow we will stay at home.", answer: "If it rains tomorrow / we will stay at home." },
      { prompt: "My father says reading is very important.", answer: "My father says / reading is very important." },
      { prompt: "Before breakfast I always brush my teeth.", answer: "Before breakfast / I always brush my teeth." },
      { prompt: "On Saturday morning we played basketball together.", answer: "On Saturday morning / we played basketball together." },
      { prompt: "Because she was tired she went to bed early.", answer: "Because she was tired / she went to bed early." },
      { prompt: "After school I usually help my parents.", answer: "After school / I usually help my parents." },
    ],
  },
  {
    id: "day4-intonation",
    title: "第三关 语调侦探",
    instruction: "请听录音，判断下列句子的语调，并填写 ↗ 或 ↘，并每句话跟读三遍。",
    type: "choice",
    items: [
      { prompt: "Are you ready?", options: ["↗", "↘"], answer: "↗" },
      { prompt: "What's your name?", options: ["↗", "↘"], answer: "↘" },
      { prompt: "I like reading English books.", options: ["↗", "↘"], answer: "↘" },
      { prompt: "Can you swim?", options: ["↗", "↘"], answer: "↗" },
      { prompt: "It's a beautiful day today.", options: ["↗", "↘"], answer: "↘" },
      { prompt: "Where do you live?", options: ["↗", "↘"], answer: "↘" },
      { prompt: "Do you like English?", options: ["↗", "↘"], answer: "↗" },
      { prompt: "Let's begin our class.", options: ["↗", "↘"], answer: "↘" },
      { prompt: "Could you open the window?", options: ["↗", "↘"], answer: "↗" },
      { prompt: "Please sit down quietly.", options: ["↗", "↘"], answer: "↘" },
    ],
  },
  {
    id: "day4-full-challenge",
    title: "第四关 全能挑战台",
    instruction: "请听录音，完成意群、重弱读和句末语调标记，并每句话跟读三遍。",
    type: "sentenceMark",
    markOptions: ["● 重读", "◯ 弱读", "/ 停顿"],
    items: [
      { prompt: "After dinner, we usually take a walk.", answer: "After dinner / we usually take a walk. ↘；◯ we / a；● dinner / usually / take / walk。" },
      { prompt: "Could you open the window, please?", answer: "Could you open the window / please? ↗；◯ Could / you / the；● open / window / please。" },
      { prompt: "If you study hard, you can achieve your dreams.", answer: "If you study hard / you can achieve your dreams. ↘；◯ If / you / you / can / your；● study / hard / achieve / dreams。" },
      { prompt: "Learning English is fun when you enjoy the process.", answer: "Learning English is fun / when you enjoy the process. ↘；◯ is / when / you / the；● Learning / English / fun / enjoy / process。" },
    ],
    answerNote: "参考：After dinner / we usually take a walk. ↘；Could you open the window, please? ↗；If you study hard / you can achieve your dreams. ↘；Learning English is fun / when you enjoy the process. ↘。",
  },
];

const DAY_5_EXERCISES = [
  {
    id: "day5-linking",
    title: "第一关 听力雷达",
    instruction: "请听录音，在相应的单词之间做出正确的连读标记 ‿，并每句话跟读三遍。",
    type: "sentenceMark",
    markOptions: ["‿ 连读"],
    items: [
      { prompt: "I want to go home.", answer: "I want to go home." },
      { prompt: "Give it to me.", answer: "Give‿it to me." },
      { prompt: "Turn it off, please.", answer: "Turn‿it‿off, please." },
      { prompt: "You can look at it carefully.", answer: "You can look‿at‿it carefully." },
      { prompt: "Take it away after class.", answer: "Take‿it‿away‿after class." },
      { prompt: "Can I have an apple?", answer: "Can‿I have‿an‿apple?" },
      { prompt: "She asked us to open it.", answer: "She asked‿us to open‿it." },
      { prompt: "Would you like an orange?", answer: "Would you like‿an‿orange?" },
    ],
  },
  {
    id: "day5-plosion",
    title: "第二关 失爆侦探",
    instruction: "请听录音，圈出所有发生失去爆破的地方，并对相应字母画上 ̚，并每句话跟读三遍。",
    type: "sentenceMark",
    markOptions: ["̚ 失爆"],
    items: [
      { prompt: "Good boy!", answer: "Good̚ boy!" },
      { prompt: "Sit down, please.", answer: "Sit̚ down, please." },
      { prompt: "Stop talking.", answer: "Stop̚ talking." },
      { prompt: "Black coffee is my favorite.", answer: "Black̚ coffee is my favorite." },
      { prompt: "Take good care of yourself.", answer: "Take good̚ care of yourself." },
      { prompt: "Next day, we went to school.", answer: "Next̚ day, we went̚ to school." },
      { prompt: "I kept quiet because it was late.", answer: "I kept̚ quiet because it was late." },
      { prompt: "Please don't forget to bring your notebook.", answer: "Please don't̚ forget̚ to bring your notebook." },
    ],
  },
  {
    id: "day5-phenomena",
    title: "第三关 语音小侦探",
    instruction: "请听录音，判断下列句子中出现了哪一种自然语流现象，然后再跟读三遍。",
    type: "choice",
    items: [
      { prompt: "Did you finish your homework?", options: ["连读", "缩读", "同化"], answer: "同化" },
      { prompt: "We'll see you tomorrow.", options: ["缩读", "连读", "省音"], answer: "缩读" },
      { prompt: "Don't you know?", options: ["失去爆破", "连读", "同化"], answer: "同化" },
      { prompt: "I'm gonna be late.", options: ["连读", "缩读", "约化表达"], answer: "约化表达" },
      { prompt: "The water is cold.", options: ["失去爆破", "闪音", "喉塞音"], answer: "闪音" },
      { prompt: "I live in Britain.", options: ["闪音", "约化表达", "喉塞音"], answer: "喉塞音" },
    ],
  },
  {
    id: "day5-dictation",
    title: "第四关 听写达人",
    instruction: "请听录音，将完整的句子写下来。注意连读、失去爆破等自然语流现象。",
    type: "dictation",
    items: [
      { prompt: "①", answer: "Put it on the table." },
      { prompt: "②", answer: "Would you like a cup of tea?" },
      { prompt: "③", answer: "I asked her to wait for me." },
      { prompt: "④", answer: "Can you help me take it out?" },
      { prompt: "⑤", answer: "We had a good time at school." },
    ],
    answerNote: "参考答案按 Day 5 第四关听写音频整理；页面提交后统一展示核对结果。",
  },
];

export const PHONETIC_CAMP_SUPPLEMENT = {
  id: "supplement",
  day: "补充练",
  title: "拓展英语故事练习",
  page: "phonetics-discourse",
  goal: "使用 Day 1-6 的语音方法完成四篇拓展故事朗读。",
  checkpoints: ["圈出不会读或不确定发音的单词", "完成词汇、短语、句型和语法笔记", "录入学生朗读并评估打分"],
  tasks: ["朗读 The Sword in the Stone", "朗读 The Boy Who Became a President", "朗读 The General Who Dreamed of an Empire", "朗读 From Britain to America"],
  audio: [
    { title: "The Sword in the Stone", src: "/audio/phonetics/camp/the-sword-in-the-stone.mp3" },
    { title: "The Boy Who Became a President", src: "/audio/phonetics/camp/the-boy-who-became-a-president.mp3" },
    { title: "The General Who Dreamed of an Empire", src: "/audio/phonetics/camp/the-general-who-dreamed-of-an-empire.mp3" },
    { title: "From Britain to America", src: "/audio/phonetics/camp/from-britain-to-america.mp3" },
  ],
  stories: DAY_7_STORIES,
  answerSections: [
    {
      title: "拓展故事核对标准",
      items: [
        "每篇故事朗读提交后，重点核对：原文完整度、意群停顿、关键词重读、句末语调、连读和失去爆破。",
        "笔记区已直接提供词汇、短语、句型、语法和朗读提示，学生可先完成自己的笔记，再提交查看参考。",
      ],
    },
  ],
};

export const PHONETIC_CAMP_APPENDIX = {
  id: "appendix",
  day: "附录",
  title: "常见字母组合的发音",
  goal: "查阅常见元音、辅音和特殊字母组合的发音规律。",
  groups: [
    {
      title: "常见元音字母组合",
      rows: [
        ["ai", "/eɪ/", "rain, train"],
        ["ay", "/eɪ/", "day, play"],
        ["ea", "/iː/", "eat, read"],
        ["ee", "/iː/", "see, green"],
        ["ie", "/iː/", "field, piece"],
        ["oa", "/əʊ/", "boat, coat"],
        ["oe", "/əʊ/", "toe, goes"],
        ["ow", "/əʊ/ 或 /aʊ/", "snow; cow"],
        ["ou", "/aʊ/", "house"],
        ["ou", "/ʌ/", "young"],
        ["oo", "/uː/ 或 /ʊ/", "moon; book"],
        ["oi", "/ɔɪ/", "coin, join"],
        ["oy", "/ɔɪ/", "boy, toy"],
        ["au", "/ɔː/", "autumn, August"],
        ["aw", "/ɔː/", "draw, saw"],
        ["ew", "/juː/ 或 /uː/", "new; flew"],
        ["ir", "/ɜː/", "bird, girl"],
        ["er", "/ɜː/", "her, term"],
        ["ur", "/ɜː/", "turn, nurse"],
        ["ar", "/ɑː/", "car, park"],
        ["or", "/ɔː/", "short, sport"],
      ],
    },
    {
      title: "常见辅音字母组合",
      rows: [
        ["sh", "/ʃ/", "ship, fish"],
        ["th", "/θ/ 或 /ð/", "think; this"],
        ["ph", "/f/", "phone, photo"],
        ["wh", "/w/", "what, white"],
        ["ng", "/ŋ/", "sing, long"],
        ["ck", "/k/", "duck, black"],
        ["ch", "/tʃ/", "chair, chicken"],
        ["tch", "/tʃ/", "watch, catch"],
        ["ge", "/dʒ/", "age, orange, large"],
        ["dge", "/dʒ/", "bridge, judge"],
        ["qu", "/kw/", "queen, quick"],
      ],
    },
    {
      title: "常常不发音的辅音字母",
      rows: [
        ["wr", "/r/", "write, wrong；w 不发音"],
        ["kn", "/n/", "know, knife；k 不发音"],
        ["gn", "/n/", "sign, gnat；g 不发音"],
        ["mb", "/m/", "lamb, climb；b 不发音"],
        ["st", "/s/", "listen, castle；t 不发音"],
        ["lf", "/f/", "half；l 不发音"],
        ["lm", "/m/", "calm；l 不发音"],
        ["ho", "/o/", "honest, hour；h 不发音"],
      ],
    },
    {
      title: "常见特殊字母组合",
      rows: [
        ["cian", "/ʃən/", "musician, magician"],
        ["tion", "/ʃən/", "station, nation"],
        ["sion", "/ʃən/ 或 /ʒən/", "discussion; television"],
        ["ture", "/tʃə(r)/", "picture, future"],
        ["sure", "/ʒə(r)/", "measure, treasure"],
      ],
    },
  ],
};

export const PHONETIC_CAMP_DAYS = [
  {
    day: "Day 1",
    title: "解锁元音小家",
    page: "phonetics-sound",
    goal: "按 a/e/i/o/u 和 +ɪ/+ʊ/+ə 两条线整理 20 个元音。",
    checkpoints: ["单元音定点发，口型保持稳定", "双元音滑着发，不把两个音断开", "能区分长元音、短元音和双元音"],
    tasks: ["听辨 /iː/ vs /ɪ/、/uː/ vs /ʊ/ 等易混元音", "把元音归入 A/E/I/O/U 家族", "跟读音标和例词并记录薄弱音"],
    audio: [
      { title: "Day 1 练习题第一关和第二关录音", src: "/audio/phonetics/camp/day1-practice-1-2.mp3" },
    ],
    sectionAudio: {
      "day1-listening-radar": [
        { title: "Day 1 第一关 听力雷达", src: "/audio/phonetics/camp/day1-level-1.mp3" },
      ],
      "day1-reading": [
        { title: "Day 1 第二关 朗读小喇叭", src: "/audio/phonetics/camp/day1-level-2.mp3" },
      ],
    },
    exerciseSections: DAY_1_EXERCISES,
    drills: [
      {
        id: "camp-d1-family",
        title: "分类工程师：元音找小家",
        type: "classify",
        options: ["A 家族", "E 家族", "I 家族", "O 家族", "U 家族", "双元音"],
        items: [
          { prompt: "/ɑː/", answer: "A 家族" },
          { prompt: "/ɜː/", answer: "E 家族" },
          { prompt: "/ɪ/", answer: "I 家族" },
          { prompt: "/ɔː/", answer: "O 家族" },
          { prompt: "/ʊ/", answer: "U 家族" },
          { prompt: "/eɪ/", answer: "双元音" },
        ],
      },
    ],
    quiz: [
      {
        id: "camp-d1-q1",
        question: "发 /eɪ/、/aɪ/、/ɔɪ/ 时，最关键的动作是什么？",
        options: ["A. 保持一个固定口型", "B. 从第一个音自然滑向 /ɪ/", "C. 把两个音分开读", "D. 只看单词拼写"],
        answer: "B",
        explanation: "双元音要一口气从第一个音滑向第二个音，/eɪ/、/aɪ/、/ɔɪ/ 属于 +ɪ 组。",
      },
      {
        id: "camp-d1-q2",
        question: "下面哪一组都是单元音？",
        options: ["A. /eɪ/ /aɪ/ /ɔɪ/", "B. /ɪə/ /eə/ /ʊə/", "C. /ɑː/ /ʌ/ /æ/", "D. /əʊ/ /aʊ/ /iː/"],
        answer: "C",
        explanation: "/ɑː/ /ʌ/ /æ/ 都属于 Aa 家族单元音。",
      },
    ],
  },
  {
    day: "Day 2",
    title: "攻克辅音怪兽",
    page: "phonetics-sound",
    goal: "用清浊对照和发音部位分类掌握辅音重点。",
    checkpoints: ["能区分清辅音和浊辅音", "能识别爆破音、摩擦音、破擦音和鼻音", "知道 /w/、/j/、/θ/、/ð/ 不等同于拼音"],
    tasks: ["听辨 /s/ vs /z/、/θ/ vs /ð/、/ʃ/ vs /ʒ/", "把辅音放入爆破音、摩擦音、破擦音等类别", "重点复听 /l/、/r/、/w/、/j/"],
    audio: [
      { title: "Day 2 练习题第一关和第二关录音", src: "/audio/phonetics/camp/day2-practice-1-2.mp3" },
    ],
    sectionAudio: {
      "day2-listening-radar": [
        { title: "Day 2 第一关 听力雷达", src: "/audio/phonetics/camp/day2-level-1.mp3" },
      ],
      "day2-reading": [
        { title: "Day 2 第二关 朗读小喇叭", src: "/audio/phonetics/camp/day2-level-2.mp3" },
      ],
    },
    exerciseSections: DAY_2_EXERCISES,
    drills: [
      {
        id: "camp-d2-type",
        title: "分类工程师：辅音归类",
        type: "classify",
        options: ["爆破音", "摩擦音", "破擦音", "鼻音", "流音", "半元音", "声门音"],
        items: [
          { prompt: "/p/", answer: "爆破音" },
          { prompt: "/θ/", answer: "摩擦音" },
          { prompt: "/dʒ/", answer: "破擦音" },
          { prompt: "/ŋ/", answer: "鼻音" },
          { prompt: "/r/", answer: "流音" },
          { prompt: "/j/", answer: "半元音" },
          { prompt: "/h/", answer: "声门音" },
        ],
      },
    ],
    quiz: [
      {
        id: "camp-d2-q1",
        question: "判断清辅音和浊辅音时，最直接的标准是什么？",
        options: ["A. 声带是否震动", "B. 单词是否重读", "C. 字母是否大写", "D. 音标是否较长"],
        answer: "A",
        explanation: "清辅音发音时声带不震动，浊辅音发音时声带震动。",
      },
      {
        id: "camp-d2-q2",
        question: "下面哪一组属于辅音连缀或补充音组？",
        options: ["A. /m/ /n/ /ŋ/", "B. /tr/ /dr/ /ts/ /dz/", "C. /f/ /v/ /θ/ /ð/", "D. /w/ /j/ /h/"],
        answer: "B",
        explanation: "/tr/ /dr/ /ts/ /dz/ 是讲义里单独强化的常见辅音组合。",
      },
    ],
  },
  {
    day: "Day 3",
    title: "音节拼词魔法",
    page: "phonetics-syllable",
    goal: "从元音音素出发，数音节、划音节、找重音、判断开闭音节。",
    checkpoints: ["数的是元音音素，不是元音字母", "会用 pa-per / rab-bit 两类基础规则划分音节", "能识别主重读、次重读和开闭音节"],
    tasks: ["给 important、holiday、computer 等词划分音节", "点击或标记重读音节", "判断 tiger、paper、picnic 等词的开闭音节"],
    exerciseSections: DAY_3_EXERCISES,
    drills: [
      {
        id: "camp-d3-syllables",
        title: "音节小侦探：用 - 划分音节",
        type: "text",
        helper: "输入示例：pa-per。大小写不敏感。",
        items: [
          { prompt: "paper", answer: "pa-per" },
          { prompt: "rabbit", answer: "rab-bit" },
          { prompt: "banana", answer: "ba-na-na" },
          { prompt: "computer", answer: "com-pu-ter" },
        ],
      },
    ],
    quiz: [
      {
        id: "camp-d3-q1",
        question: "rain /reɪn/ 只有一个音节，是因为：",
        options: ["A. ai 对应一个元音音素 /eɪ/", "B. rain 没有元音字母", "C. r 是元音", "D. n 不发音"],
        answer: "A",
        explanation: "判断音节数量看元音音素，ai 虽有两个字母，但只发一个 /eɪ/。",
      },
      {
        id: "camp-d3-q2",
        question: "pa-per、ti-ger 这类词的常见划分规律是：",
        options: ["A. 两个元音字母之间一个辅音，辅音通常归后", "B. 所有辅音都归前", "C. 只按字母数量平均分", "D. 不需要结合音标验证"],
        answer: "A",
        explanation: "两个元音字母之间只有一个辅音字母时，通常把辅音放到后一个音节。",
      },
    ],
  },
  {
    day: "Day 4",
    title: "掌握句子韵律",
    page: "phonetics-sentence",
    goal: "给句子标出重读、弱读、意群停顿和语调。",
    checkpoints: ["实词通常重读，功能词通常弱读", "按意群停顿，不逐词停顿", "陈述句/特殊疑问句降调，一般疑问句升调"],
    tasks: ["用 ●/○ 标记重弱读", "用 / 划分意群", "判断句末 ↗ 或 ↘"],
    audio: [
      { title: "Day 4 练习题音频", src: "/audio/phonetics/camp/day4-practice.mp3" },
    ],
    sectionAudio: {
      "day4-stress": [
        { title: "Day 4 第一关 听力雷达", src: "/audio/phonetics/camp/day4-level-1.mp3" },
      ],
      "day4-sense-groups": [
        { title: "Day 4 第二关 节奏工程师", src: "/audio/phonetics/camp/day4-level-2.mp3" },
      ],
      "day4-intonation": [
        { title: "Day 4 第三关 语调侦探", src: "/audio/phonetics/camp/day4-level-3.mp3" },
      ],
      "day4-full-challenge": [
        { title: "Day 4 第四关 全能挑战台", src: "/audio/phonetics/camp/day4-level-4.mp3" },
      ],
    },
    exerciseSections: DAY_4_EXERCISES,
    drills: [
      {
        id: "camp-d4-intonation",
        title: "语调判断：句末升降调",
        type: "classify",
        options: ["↗ 升调", "↘ 降调"],
        items: [
          { prompt: "Are you ready?", answer: "↗ 升调" },
          { prompt: "What's your name?", answer: "↘ 降调" },
          { prompt: "I like reading English books.", answer: "↘ 降调" },
          { prompt: "Can you swim?", answer: "↗ 升调" },
          { prompt: "Where do you live?", answer: "↘ 降调" },
          { prompt: "Please sit down quietly.", answer: "↘ 降调" },
        ],
      },
      {
        id: "camp-d4-sense-groups",
        title: "意群切分：用 / 标出停顿",
        type: "text",
        helper: "输入示例：After dinner / we usually take a walk. 标点和空格不必完全一致。",
        items: [
          { prompt: "After dinner, we usually take a walk.", answer: "After dinner / we usually take a walk" },
          { prompt: "If you study hard, you can achieve your dreams.", answer: "If you study hard / you can achieve your dreams" },
          { prompt: "On Saturday morning we played basketball together.", answer: "On Saturday morning / we played basketball together" },
        ],
      },
    ],
    answerSections: [
      {
        title: "重弱读参考",
        items: [
          "重读：名词、实义动词、形容词、副词、时间/地点核心信息通常标 ●。",
          "弱读：I、we、you、a、the、to、of、for、and、can、have 等功能词通常标 ○。",
        ],
      },
      {
        title: "停顿与语调参考",
        items: [
          "After dinner / we usually take a walk. ↘",
          "If you study hard / you can achieve your dreams. ↘",
          "Are you ready? ↗；What's your name? ↘；I like reading English books. ↘；Can you swim? ↗。",
        ],
      },
    ],
  },
  {
    day: "Day 5",
    title: "破解语流密码",
    page: "phonetics-sentence",
    goal: "识别连读、失去爆破、同化和常见弱化。",
    checkpoints: ["辅音 + 元音可连读", "爆破音 + 辅音常失去爆破", "/t d s z/ + /j/ 可发生同化"],
    tasks: ["标记 pick it、stand up 的连读", "标记 good boy 的失去爆破", "识别 did you、would you 的同化"],
    audio: [
      { title: "Day 5 练习题音频", src: "/audio/phonetics/camp/day5-practice.mp3" },
    ],
    sectionAudio: {
      "day5-linking": [
        { title: "Day 5 第一关 听力雷达", src: "/audio/phonetics/camp/day5-level-1.mp3" },
      ],
      "day5-plosion": [
        { title: "Day 5 第二关 失爆侦探", src: "/audio/phonetics/camp/day5-level-2.mp3" },
      ],
      "day5-phenomena": [
        { title: "Day 5 第三关 语音小侦探", src: "/audio/phonetics/camp/day5-level-3.mp3" },
      ],
      "day5-dictation": [
        { title: "Day 5 第四关 听写达人", src: "/audio/phonetics/camp/day5-level-4.mp3" },
      ],
    },
    exerciseSections: DAY_5_EXERCISES,
    drills: [
      {
        id: "camp-d5-stream-types",
        title: "语流识别：判断现象类型",
        type: "classify",
        options: ["连读", "失去爆破", "同化", "约化", "省音/弱化"],
        items: [
          { prompt: "pick it", answer: "连读" },
          { prompt: "good boy", answer: "失去爆破" },
          { prompt: "did you", answer: "同化" },
          { prompt: "want to", answer: "约化" },
          { prompt: "next day", answer: "省音/弱化" },
        ],
      },
      {
        id: "camp-d5-stream-marks",
        title: "语流标注：写出推荐标记",
        type: "text",
        helper: "可直接输入符号答案，例如 stand‿up 或 sit̚ down。",
        items: [
          { prompt: "stand up", answer: "stand‿up" },
          { prompt: "sit down", answer: "sit̚ down" },
          { prompt: "would you", answer: "would you → /wʊdʒə/" },
        ],
      },
    ],
    answerSections: [
      {
        title: "语流现象参考",
        items: [
          "连读：pick‿it、stand‿up、look‿at、an‿apple。",
          "失去爆破：good̚ boy、sit̚ down、black̚ cat、must̚ go。",
          "同化：did you → /dɪdʒə/；would you → /wʊdʒə/；miss you → /mɪʃuː/。",
          "省音/弱化：want to 可约化为 wanna；going to 可约化为 gonna；next day 中 /t/ 可弱化或省音。",
        ],
      },
    ],
  },
  {
    day: "Day 6",
    title: "走进英语故事",
    page: "phonetics-discourse",
    goal: "把音素、音节、韵律和语流放进故事朗读。",
    checkpoints: ["能逐句听原音", "能看懂系统标注", "能整理词汇、短语、句型和语法笔记"],
    tasks: ["练习 The Tea Party", "先自己标注，再对照 AI 标注", "逐句跟读后播放全文"],
    audio: [
      { title: "The Tea Party", src: "/audio/phonetics/camp/the-tea-party.mp3" },
    ],
    stories: [TEA_PARTY_STORY],
    answerSections: [
      {
        title: "朗读核对标准",
        items: ["故事朗读没有唯一书面答案；以 AI 标注中的 ●/○、/、‿、̚、→、↗/↘ 为核对标准。"],
      },
      {
        title: "笔记参考",
        items: [
          "词汇、短语、句型、语法和朗读提示已在本日“故事原文与笔记区”完整列出。",
          "建议学生先遮住笔记复述故事，再用笔记补充历史背景词汇和语音标注。",
        ],
      },
    ],
  },
  {
    day: "Day 7",
    title: "成为朗读达人",
    page: "phonetics-discourse",
    goal: "完成一篇完整故事朗读，并用自评卡复盘。",
    checkpoints: ["发音准确度", "朗读流利度", "节奏与语调", "自信表达"],
    tasks: ["选择一篇故事完整朗读", "圈出不确定发音的单词", "按四项自评卡记录表现"],
    audio: [
      { title: "The Tea Party", src: "/audio/phonetics/camp/the-tea-party.mp3" },
      { title: "The Sword in the Stone", src: "/audio/phonetics/camp/the-sword-in-the-stone.mp3" },
      { title: "The Boy Who Became a President", src: "/audio/phonetics/camp/the-boy-who-became-a-president.mp3" },
      { title: "The General Who Dreamed of an Empire", src: "/audio/phonetics/camp/the-general-who-dreamed-of-an-empire.mp3" },
      { title: "From Britain to America", src: "/audio/phonetics/camp/from-britain-to-america.mp3" },
    ],
    stories: [TEA_PARTY_STORY, ...DAY_7_STORIES],
    rubric: [
      "发音准确度 1-5 星：元音长度、辅音清浊、/θ/ /ð/ /r/ /l/ /w/ /j/ 等重点音是否清楚。",
      "朗读流利度 1-5 星：是否能按意群自然推进，是否避免逐词停顿和频繁回读。",
      "节奏与语调 1-5 星：重读词是否突出，功能词是否弱读，陈述句/特殊疑问句是否自然降调，一般疑问句是否升调。",
      "自信表达 1-5 星：音量、语速、停顿、角色对话和故事情绪是否稳定自然。",
      "复盘建议：总分 18-20 星可挑战无字幕朗读；14-17 星回听错音句；13 星及以下先回到 Day 1-5 对应技能点重练。",
    ],
    answerSections: [
      {
        title: "自评卡参考",
        items: [
          "朗读展示没有唯一标准答案；按发音准确度、朗读流利度、节奏与语调、自信表达四项自评。",
          "建议每项 1-5 星，满分 20 星；低于 14 星时回到对应故事音频逐句跟读。",
        ],
      },
    ],
  },
];
