// 词汇模块内容库：阅读/写作分类词表与同义替换表（供词汇检测、资源页等使用）

/* ── Reading vocab data (moved from ReadingVocabPage) ───────── */
export const READING_CATEGORIES = [
  {
    id: "academic",
    label: "学术词汇",
    desc: "高频学术语境词",
    icon: "🎓",
    words: [
      { word: "analyze",      pos: "v.",     phonetic: "/ˈænəlaɪz/",       zh: "分析；研究",        example: "Scientists analyze data to draw conclusions.",                    tip: "analyze = break down into parts" },
      { word: "significant",  pos: "adj.",   phonetic: "/sɪɡˈnɪfɪkənt/",   zh: "重要的；显著的",    example: "The study found a significant difference between the two groups.", tip: "关联词：significance (n.), significantly (adv.)" },
      { word: "evidence",     pos: "n.",     phonetic: "/ˈevɪdəns/",        zh: "证据；迹象",        example: "The author provides evidence to support each claim.",             tip: "evidence-based = 以证据为基础的" },
      { word: "perspective",  pos: "n.",     phonetic: "/pəˈspektɪv/",      zh: "视角；观点",        example: "From a historical perspective, the event was pivotal.",          tip: "from a ... perspective = 从……角度来看" },
      { word: "controversy",  pos: "n.",     phonetic: "/ˈkɒntrəvɜːsi/",   zh: "争议；争论",        example: "The policy sparked great controversy among experts.",             tip: "controversial (adj.) = 有争议的" },
      { word: "fundamental",  pos: "adj.",   phonetic: "/ˌfʌndəˈmentəl/",  zh: "基础的；根本的",    example: "Access to clean water is a fundamental human right.",             tip: "= basic, essential, core" },
      { word: "inevitably",   pos: "adv.",   phonetic: "/ɪnˈevɪtəbli/",    zh: "不可避免地",        example: "Rapid growth inevitably leads to growing pains.",                tip: "inevitable (adj.) = 不可避免的" },
      { word: "consequence",  pos: "n.",     phonetic: "/ˈkɒnsɪkwəns/",    zh: "结果；后果",        example: "The consequences of climate change are already visible.",        tip: "as a consequence = 因此" },
      { word: "perceive",     pos: "v.",     phonetic: "/pəˈsiːv/",         zh: "感知；认为",        example: "How we perceive a problem shapes how we solve it.",              tip: "perception (n.) = 感知；看法" },
      { word: "equivalent",   pos: "adj./n.",phonetic: "/ɪˈkwɪvələnt/",   zh: "等同的；等价物",    example: "One hour of study is equivalent to three hours of passive reading.", tip: "be equivalent to = 相当于" },
      { word: "approach",     pos: "n./v.",   phonetic: "/əˈprəʊtʃ/",       zh: "方法；接近；处理",  example: "The article compares two different approaches to education.",    tip: "an approach to doing sth. = 做某事的方法" },
      { word: "concept",      pos: "n.",      phonetic: "/ˈkɒnsept/",       zh: "概念；观念",        example: "The concept of fairness changes across cultures.",               tip: "conceptual (adj.) = 概念上的" },
      { word: "context",      pos: "n.",      phonetic: "/ˈkɒntekst/",      zh: "语境；背景",        example: "The meaning of a word depends heavily on context.",              tip: "in context = 在语境中" },
      { word: "criteria",     pos: "n.",      phonetic: "/kraɪˈtɪəriə/",    zh: "标准；准则",        example: "The research uses clear criteria to evaluate success.",          tip: "criterion 的复数；阅读说明文常见" },
      { word: "derive",       pos: "v.",      phonetic: "/dɪˈraɪv/",        zh: "获得；源于",        example: "Many English words derive from Latin.",                          tip: "derive from = 来源于" },
      { word: "factor",       pos: "n.",      phonetic: "/ˈfæktə/",         zh: "因素；要素",        example: "Cost is only one factor in the final decision.",                 tip: "contributing factor = 影响因素" },
      { word: "function",     pos: "n./v.",   phonetic: "/ˈfʌŋkʃən/",       zh: "功能；运转",        example: "Sleep performs an important function in memory.",               tip: "function as = 起……作用" },
      { word: "interpret",    pos: "v.",      phonetic: "/ɪnˈtɜːprɪt/",     zh: "解释；理解",        example: "Readers may interpret the ending in different ways.",           tip: "interpretation (n.) = 解读" },
      { word: "principle",    pos: "n.",      phonetic: "/ˈprɪnsəpl/",      zh: "原则；原理",        example: "The principle applies to many areas of science.",               tip: "in principle = 原则上" },
      { word: "process",      pos: "n./v.",   phonetic: "/ˈprəʊses/",       zh: "过程；处理",        example: "Learning a language is a gradual process.",                     tip: "process information = 处理信息" },
      { word: "range",        pos: "n./v.",   phonetic: "/reɪndʒ/",         zh: "范围；变化",        example: "The survey covers a wide range of age groups.",                 tip: "a range of = 一系列" },
      { word: "role",         pos: "n.",      phonetic: "/rəʊl/",           zh: "角色；作用",        example: "Parents play a crucial role in early learning.",                tip: "play a role in = 在……中起作用" },
      { word: "structure",    pos: "n./v.",   phonetic: "/ˈstrʌktʃə/",      zh: "结构；组织",        example: "The structure of the passage makes the argument clear.",        tip: "text structure = 文章结构" },
      { word: "variable",     pos: "n./adj.", phonetic: "/ˈveəriəbl/",      zh: "变量；可变的",      example: "Age was an important variable in the experiment.",              tip: "阅读研究类文章高频" },
      { word: "widespread",   pos: "adj.",    phonetic: "/ˈwaɪdspred/",     zh: "广泛的；普遍的",    example: "The new policy received widespread public support.",            tip: "= common, extensive" },
    ],
  },
  {
    id: "inference",
    label: "推断常用词",
    desc: "推断题高频词汇",
    icon: "🔍",
    words: [
      { word: "imply",           pos: "v.",   phonetic: "/ɪmˈplaɪ/",           zh: "暗示；意味着",   example: "The data implies that the trend will continue.",              tip: "imply ≠ state directly；作者暗示而未明说" },
      { word: "suggest",         pos: "v.",   phonetic: "/səˈdʒest/",           zh: "表明；暗示",     example: "The author suggests that technology has its limits.",          tip: "suggest 在阅读中常等于 imply" },
      { word: "indicate",        pos: "v.",   phonetic: "/ˈɪndɪkeɪt/",         zh: "表明；指示",     example: "The results indicate a need for further research.",           tip: "indication (n.) = 迹象；信号" },
      { word: "infer",           pos: "v.",   phonetic: "/ɪnˈfɜː/",            zh: "推断；推论",     example: "From the context, we can infer the author's attitude.",       tip: "inference (n.) = 推断；推论" },
      { word: "assume",          pos: "v.",   phonetic: "/əˈsjuːm/",           zh: "假设；认为",     example: "The author assumes readers are familiar with the topic.",     tip: "assumption (n.) = 假设；前提" },
      { word: "paradox",         pos: "n.",   phonetic: "/ˈpærədɒks/",         zh: "悖论；矛盾现象", example: "It's a paradox that the busiest people often have the most time.", tip: "paradoxically = 看似矛盾地" },
      { word: "counterintuitive",pos: "adj.", phonetic: "/ˌkaʊntərɪnˈtjuːɪtɪv/", zh: "违反直觉的",  example: "It may seem counterintuitive, but rest can boost productivity.", tip: "counter- = 反、对抗" },
      { word: "reveal",          pos: "v.",   phonetic: "/rɪˈviːl/",           zh: "揭示；显示",     example: "The study reveals a gap between theory and practice.",        tip: "revelation (n.) = 揭示；启示" },
      { word: "conclude",        pos: "v.",   phonetic: "/kənˈkluːd/",         zh: "得出结论；结束", example: "We can conclude from the evidence that the method works.",   tip: "conclusion (n.) = 结论" },
      { word: "deduce",          pos: "v.",   phonetic: "/dɪˈdjuːs/",          zh: "推论；演绎",     example: "The detective deduced the truth from small details.",        tip: "比 infer 更偏逻辑推理" },
      { word: "evidently",       pos: "adv.", phonetic: "/ˈevɪdəntli/",        zh: "显然；明显地",   example: "Evidently, the old explanation is incomplete.",              tip: "= clearly, apparently" },
      { word: "presumably",      pos: "adv.", phonetic: "/prɪˈzjuːməbli/",     zh: "大概；推测起来", example: "Presumably, the author wanted readers to question the claim.", tip: "表示基于已知信息的推测" },
      { word: "underlying",      pos: "adj.", phonetic: "/ˌʌndəˈlaɪɪŋ/",       zh: "潜在的；根本的", example: "The passage explores the underlying causes of stress.",     tip: "underlying reason/cause = 深层原因" },
      { word: "plausible",       pos: "adj.", phonetic: "/ˈplɔːzəbl/",         zh: "貌似合理的",     example: "The explanation sounds plausible, but it lacks evidence.",   tip: "常用于判断选项是否合理" },
      { word: "ambiguous",       pos: "adj.", phonetic: "/æmˈbɪɡjuəs/",        zh: "模棱两可的",     example: "The author's attitude remains ambiguous until the final paragraph.", tip: "ambiguity (n.) = 歧义" },
    ],
  },
  {
    id: "attitude",
    label: "态度情感词",
    desc: "作者态度题关键词",
    icon: "💬",
    words: [
      { word: "skeptical",  pos: "adj.", phonetic: "/ˈskeptɪkəl/",    zh: "怀疑的",       example: "Many researchers remain skeptical about the findings.",        tip: "= doubtful; 比 critical 更温和" },
      { word: "optimistic", pos: "adj.", phonetic: "/ˌɒptɪˈmɪstɪk/",  zh: "乐观的",       example: "The author is cautiously optimistic about renewable energy.",   tip: "optimism (n.) / pessimistic = 悲观" },
      { word: "dismissive", pos: "adj.", phonetic: "/dɪsˈmɪsɪv/",     zh: "轻蔑的",       example: "Critics were dismissive of the new theory.",                   tip: "dismiss (v.) = 驳回；不以为然" },
      { word: "admiring",   pos: "adj.", phonetic: "/ədˈmaɪərɪŋ/",    zh: "钦佩的",       example: "The biographer writes in an admiring tone.",                   tip: "admire (v.) / admiration (n.)" },
      { word: "cautious",   pos: "adj.", phonetic: "/ˈkɔːʃəs/",       zh: "谨慎的",       example: "Scientists are cautious about making definitive claims.",       tip: "caution (n.) = 谨慎" },
      { word: "critical",   pos: "adj.", phonetic: "/ˈkrɪtɪkəl/",     zh: "批判的；关键的", example: "The author is critical of the government's response.",         tip: "注意双义：批判的 / 极重要的" },
      { word: "indifferent",pos: "adj.", phonetic: "/ɪnˈdɪfərənt/",   zh: "漠然的",       example: "The public seemed largely indifferent to the issue.",          tip: "通常是阅读态度题的错误选项" },
      { word: "nostalgic",  pos: "adj.", phonetic: "/nɒˈstælɪk/",     zh: "怀旧的",       example: "The essay has a nostalgic tone about childhood.",              tip: "nostalgia (n.) = 对过去的留恋" },
      { word: "objective",  pos: "adj.", phonetic: "/əbˈdʒektɪv/",    zh: "客观的",       example: "The report takes an objective view of the problem.",           tip: "objective tone = 客观语气" },
      { word: "subjective", pos: "adj.", phonetic: "/səbˈdʒektɪv/",   zh: "主观的",       example: "Personal memories are often subjective.",                      tip: "与 objective 相对" },
      { word: "approving",  pos: "adj.", phonetic: "/əˈpruːvɪŋ/",     zh: "赞许的",       example: "The writer sounds approving of the students' efforts.",        tip: "approve of = 赞成" },
      { word: "neutral",    pos: "adj.", phonetic: "/ˈnjuːtrəl/",     zh: "中立的",       example: "The article uses a mostly neutral tone.",                      tip: "不明显支持也不反对" },
      { word: "concerned",  pos: "adj.", phonetic: "/kənˈsɜːnd/",     zh: "担忧的；关切的", example: "The author is concerned about the loss of biodiversity.",     tip: "be concerned about = 担心" },
      { word: "sympathetic",pos: "adj.", phonetic: "/ˌsɪmpəˈθetɪk/",  zh: "同情的；支持的", example: "The narrator is sympathetic toward the old man.",             tip: "sympathy (n.) = 同情" },
      { word: "ironic",     pos: "adj.", phonetic: "/aɪˈrɒnɪk/",      zh: "讽刺的；反讽的", example: "The ending has an ironic twist.",                            tip: "irony (n.) = 反讽" },
      { word: "reserved",   pos: "adj.", phonetic: "/rɪˈzɜːvd/",      zh: "保留的；克制的", example: "The scientist gave a reserved response to the new claim.",    tip: "reserved attitude = 保留态度" },
    ],
  },
  {
    id: "transition",
    label: "逻辑衔接词",
    desc: "文章结构与论证词",
    icon: "🔗",
    words: [
      { word: "nevertheless", pos: "adv.",  phonetic: "/ˌnevəðəˈles/",   zh: "尽管如此",  example: "The task was difficult. Nevertheless, they succeeded.",       tip: "= however; 转折后往往是作者真实观点" },
      { word: "consequently", pos: "adv.",  phonetic: "/ˈkɒnsɪkwəntli/", zh: "因此；结果", example: "The factory closed, and consequently hundreds lost jobs.",    tip: "= therefore, as a result; 表因果" },
      { word: "furthermore",  pos: "adv.",  phonetic: "/ˌfɜːðəˈmɔː/",   zh: "此外；而且", example: "The plan is cost-effective. Furthermore, it is eco-friendly.", tip: "= moreover; 递进关系" },
      { word: "albeit",       pos: "conj.", phonetic: "/ɔːlˈbiːɪt/",     zh: "尽管；虽然", example: "The results were positive, albeit inconclusive.",             tip: "= although; 常插入句中修饰" },
      { word: "nonetheless",  pos: "adv.",  phonetic: "/ˌnʌnðəˈles/",   zh: "尽管如此",  example: "The evidence is limited; nonetheless, it points to a trend.", tip: "= nevertheless; 可互换" },
      { word: "whereas",      pos: "conj.", phonetic: "/werˈæz/",         zh: "然而；而",   example: "Mammals are warm-blooded, whereas reptiles are cold-blooded.", tip: "= while; 用于对比两件事" },
      { word: "thereby",      pos: "adv.",  phonetic: "/ˌðeəˈbaɪ/",      zh: "从而；因此", example: "They reduced costs, thereby increasing profits.",             tip: "= by doing so; 通常接分词短语" },
      { word: "conversely",   pos: "adv.",  phonetic: "/ˈkɒnvɜːsli/",   zh: "相反地",    example: "More exercise reduces stress; conversely, inactivity increases it.", tip: "= on the other hand; 对比关系" },
      { word: "accordingly",  pos: "adv.",  phonetic: "/əˈkɔːdɪŋli/",    zh: "因此；相应地", example: "The evidence changed; accordingly, the conclusion was revised.", tip: "正式因果衔接词" },
      { word: "alternatively",pos: "adv.",  phonetic: "/ɔːlˈtɜːnətɪvli/",zh: "或者；另一种选择", example: "Alternatively, students can complete the task online.", tip: "提出另一种方案" },
      { word: "despite",      pos: "prep.", phonetic: "/dɪˈspaɪt/",      zh: "尽管",       example: "Despite the difficulties, the team finished the project.",     tip: "despite + 名词/动名词" },
      { word: "likewise",     pos: "adv.",  phonetic: "/ˈlaɪkwaɪz/",     zh: "同样地",     example: "The first method saves time; likewise, the second reduces cost.", tip: "并列相似关系" },
      { word: "meanwhile",    pos: "adv.",  phonetic: "/ˈmiːnwaɪl/",     zh: "与此同时",   example: "Demand increased. Meanwhile, supply remained limited.",        tip: "时间或对比衔接" },
      { word: "otherwise",    pos: "adv.",  phonetic: "/ˈʌðəwaɪz/",      zh: "否则；除此以外", example: "Follow the instructions; otherwise, the result may be wrong.", tip: "条件后果关系" },
      { word: "similarly",    pos: "adv.",  phonetic: "/ˈsɪmələli/",     zh: "相似地",     example: "Similarly, young children learn through repeated practice.",   tip: "类比衔接" },
      { word: "subsequently", pos: "adv.",  phonetic: "/ˈsʌbsɪkwəntli/", zh: "随后；后来", example: "The theory was subsequently tested in several countries.",      tip: "时间顺序" },
      { word: "ultimately",   pos: "adv.",  phonetic: "/ˈʌltɪmətli/",    zh: "最终；归根结底", example: "Ultimately, the decision depends on public support.",       tip: "结论段常见" },
      { word: "in contrast",  pos: "phrase",phonetic: "/ɪn ˈkɒntrɑːst/", zh: "相比之下",   example: "In contrast, the second group showed little improvement.",     tip: "强对比关系" },
    ],
  },
  {
    id: "narrative",
    label: "记叙文词汇",
    desc: "人物叙事高频词",
    icon: "📖",
    words: [
      { word: "reminisce",     pos: "v.",   phonetic: "/ˌremɪˈnɪs/",      zh: "回忆；追忆",    example: "She reminisced about her childhood summers by the sea.",   tip: "reminiscence (n.) = 回忆录" },
      { word: "resilient",     pos: "adj.", phonetic: "/rɪˈzɪliənt/",     zh: "有韧性的",      example: "Despite setbacks, she remained resilient.",                tip: "resilience (n.) = 韧性；复原力" },
      { word: "bittersweet",   pos: "adj.", phonetic: "/ˈbɪtəswiːt/",     zh: "苦乐参半的",    example: "The farewell was bittersweet — sad but full of gratitude.", tip: "常出现在叙事文结尾" },
      { word: "epiphany",      pos: "n.",   phonetic: "/ɪˈpɪfəni/",       zh: "顿悟；突然明白", example: "The moment was an epiphany — he finally understood.",       tip: "叙事文人物'领悟'的高级表达" },
      { word: "perseverance",  pos: "n.",   phonetic: "/ˌpɜːsɪˈvɪərəns/", zh: "坚持不懈；毅力", example: "Her perseverance paid off in the end.",                    tip: "persevere (v.) = 坚持；不放弃" },
      { word: "solitude",      pos: "n.",   phonetic: "/ˈsɒlɪtjuːd/",     zh: "独处；孤独",    example: "He found comfort in solitude, away from the noise.",       tip: "≠ loneliness；solitude 是主动选择" },
      { word: "transformation",pos: "n.",   phonetic: "/ˌtrænsfəˈmeɪʃən/",zh: "转变；改变",    example: "The experience led to a profound personal transformation.", tip: "transform (v.) = 彻底改变" },
      { word: "anticipation",  pos: "n.",   phonetic: "/ænˌtɪsɪˈpeɪʃən/", zh: "期待；预期",    example: "She waited in quiet anticipation.",                       tip: "in anticipation of = 期待；预先" },
      { word: "bewildered",    pos: "adj.", phonetic: "/bɪˈwɪldəd/",      zh: "困惑的",        example: "He looked bewildered by the sudden change.",                tip: "= confused, puzzled" },
      { word: "compassion",    pos: "n.",   phonetic: "/kəmˈpæʃən/",      zh: "同情；怜悯",    example: "Her compassion made the lonely child feel seen.",          tip: "compassionate (adj.) = 有同情心的" },
      { word: "determination", pos: "n.",   phonetic: "/dɪˌtɜːmɪˈneɪʃən/",zh: "决心；坚定",    example: "His determination helped him overcome every obstacle.",     tip: "with determination = 坚定地" },
      { word: "gratitude",     pos: "n.",   phonetic: "/ˈɡrætɪtjuːd/",    zh: "感激",          example: "She smiled with gratitude after receiving the letter.",     tip: "show gratitude to = 向……表达感谢" },
      { word: "hesitate",      pos: "v.",   phonetic: "/ˈhezɪteɪt/",      zh: "犹豫",          example: "He hesitated before opening the door.",                    tip: "without hesitation = 毫不犹豫" },
      { word: "relief",        pos: "n.",   phonetic: "/rɪˈliːf/",        zh: "宽慰；缓解",    example: "To her relief, the missing dog returned home.",            tip: "to one's relief = 令某人宽慰的是" },
      { word: "tremble",       pos: "v.",   phonetic: "/ˈtrembl/",        zh: "颤抖",          example: "His hands trembled as he read the result.",                tip: "常用于紧张、寒冷、激动" },
      { word: "vivid",         pos: "adj.", phonetic: "/ˈvɪvɪd/",         zh: "生动的；鲜明的", example: "The story creates a vivid picture of village life.",       tip: "vivid description = 生动描写" },
    ],
  },
];

/* ── Writing vocab data ─────────────────────────────────────── */
export const WRITING_CATEGORIES = [
  {
    id: "writing-core",
    label: "写作核心词",
    desc: "议论文高分表达词汇",
    icon: "✍️",
    words: [
      { word: "advocate",     pos: "v./n.", phonetic: "/ˈædvəkeɪt/",     zh: "提倡；支持者",   example: "Many experts advocate a shift to renewable energy.",           tip: "advocate for = 倡导；名词时 = 倡导者" },
      { word: "contend",      pos: "v.",    phonetic: "/kənˈtend/",       zh: "主张；争论",     example: "The author contends that technology is a double-edged sword.", tip: "contention (n.) = 论点；争论" },
      { word: "substantiate", pos: "v.",    phonetic: "/səbˈstænʃieɪt/", zh: "证实；支持",     example: "Statistics substantiate the claim that exercise boosts mood.",  tip: "= support, back up; 比 show 更书面" },
      { word: "exemplify",    pos: "v.",    phonetic: "/ɪɡˈzemplɪfaɪ/",  zh: "例证；举例说明", example: "This case exemplifies the broader problem of inequality.",       tip: "= illustrate with an example" },
      { word: "underscore",   pos: "v.",    phonetic: "/ˌʌndəˈskɔː/",    zh: "强调；突出",     example: "The data underscores the urgency of climate action.",           tip: "= emphasize, highlight; 议论文高频" },
      { word: "mitigate",     pos: "v.",    phonetic: "/ˈmɪtɪɡeɪt/",     zh: "减轻；缓和",     example: "Governments must take steps to mitigate the effects of poverty.", tip: "= alleviate, reduce; 常用于问题解决" },
      { word: "exacerbate",   pos: "v.",    phonetic: "/ɪɡˈzæsəbeɪt/",  zh: "加剧；恶化",     example: "Inequality can exacerbate social tension and unrest.",           tip: "= worsen, aggravate; 与 mitigate 对立" },
      { word: "foster",       pos: "v.",    phonetic: "/ˈfɒstə/",         zh: "促进；培养",     example: "Education fosters critical thinking and creativity.",            tip: "= cultivate, nurture; 正面词" },
      { word: "perpetuate",   pos: "v.",    phonetic: "/pəˈpetʃueɪt/",   zh: "使持续；延续",   example: "Media stereotypes perpetuate harmful social norms.",            tip: "= sustain, maintain; 常用于负面语境" },
      { word: "encapsulate",  pos: "v.",    phonetic: "/ɪnˈkæpsjuleɪt/", zh: "概括；总结",     example: "This quote encapsulates the author's central argument.",        tip: "= summarize; 结尾段高分替换" },
      { word: "articulate",   pos: "v.",    phonetic: "/ɑːˈtɪkjuleɪt/",  zh: "清晰表达",       example: "She articulates her views on education with great clarity.",    tip: "adj. = 表达清晰的；语言表达能力强" },
      { word: "acknowledge",  pos: "v.",    phonetic: "/əkˈnɒlɪdʒ/",     zh: "承认；认可",     example: "We must acknowledge the limitations of this approach.",        tip: "让步段常用：承认对方有一点道理" },
      { word: "circumvent",   pos: "v.",    phonetic: "/ˌsɜːkəmˈvent/",  zh: "规避；绕过",     example: "Some companies circumvent regulations through loopholes.",      tip: "= bypass, avoid; 批评语境常见" },
      { word: "engender",     pos: "v.",    phonetic: "/ɪnˈdʒendə/",     zh: "引起；导致",     example: "Poverty can engender a cycle of deprivation and crime.",        tip: "= cause, generate; 比 cause 更书面" },
      { word: "cultivate",    pos: "v.",    phonetic: "/ˈkʌltɪveɪt/",    zh: "培养；培育",     example: "Schools should cultivate a love of learning in students.",     tip: "= foster, develop; 带有积极含义" },
      { word: "enhance",      pos: "v.",    phonetic: "/ɪnˈhɑːns/",      zh: "提升；增强",     example: "Reading widely can enhance students' language awareness.",      tip: "= improve; 写作中比 make better 更自然" },
      { word: "facilitate",   pos: "v.",    phonetic: "/fəˈsɪlɪteɪt/",   zh: "促进；使便利",   example: "Technology facilitates communication across long distances.",   tip: "= make easier" },
      { word: "hinder",       pos: "v.",    phonetic: "/ˈhɪndə/",         zh: "阻碍",           example: "Excessive screen time may hinder children's social development.", tip: "与 facilitate 对立" },
      { word: "allocate",     pos: "v.",    phonetic: "/ˈæləkeɪt/",       zh: "分配；配置",     example: "Schools should allocate more resources to mental health education.", tip: "allocate resources/time = 分配资源/时间" },
      { word: "implement",    pos: "v.",    phonetic: "/ˈɪmplɪment/",    zh: "实施；执行",     example: "The government needs to implement stricter safety standards.",  tip: "implementation (n.) = 实施" },
      { word: "promote",      pos: "v.",    phonetic: "/prəˈməʊt/",       zh: "促进；推广",     example: "Community service promotes a sense of responsibility.",        tip: "promote awareness = 提高意识" },
      { word: "undermine",    pos: "v.",    phonetic: "/ˌʌndəˈmaɪn/",    zh: "削弱；损害",     example: "Cheating undermines trust in the education system.",           tip: "常用于负面影响" },
      { word: "prioritize",   pos: "v.",    phonetic: "/praɪˈɒrətaɪz/",   zh: "优先考虑",       example: "Students should prioritize deep learning over quick scores.",   tip: "prioritize A over B = 优先考虑 A" },
      { word: "address",      pos: "v.",    phonetic: "/əˈdres/",         zh: "处理；解决",     example: "Society must address the root causes of inequality.",          tip: "address a problem/issue = 解决问题" },
      { word: "balance",      pos: "v./n.", phonetic: "/ˈbæləns/",        zh: "平衡",           example: "Teenagers need to balance academic pressure and personal interests.", tip: "strike a balance = 取得平衡" },
    ],
  },
  {
    id: "writing-argument",
    label: "议论文论证词",
    desc: "观点、原因、影响与解决方案",
    icon: "🧭",
    words: [
      { word: "compelling",    pos: "adj.",   phonetic: "/kəmˈpelɪŋ/",     zh: "有说服力的",     example: "The author offers a compelling argument for public transport.", tip: "compelling evidence/reason = 有力证据/理由" },
      { word: "rationale",     pos: "n.",     phonetic: "/ˌræʃəˈnɑːl/",    zh: "理由；依据",     example: "The rationale behind the policy is easy to understand.",       tip: "正式写作中替代 reason" },
      { word: "trade-off",     pos: "n.",     phonetic: "/ˈtreɪd ɒf/",     zh: "权衡；取舍",     example: "There is a trade-off between convenience and privacy.",        tip: "between A and B" },
      { word: "drawback",      pos: "n.",     phonetic: "/ˈdrɔːbæk/",      zh: "缺点；弊端",     example: "One major drawback of online learning is distraction.",        tip: "= disadvantage" },
      { word: "merit",         pos: "n.",     phonetic: "/ˈmerɪt/",        zh: "优点；价值",     example: "The proposal has clear merits despite its high cost.",         tip: "merits and drawbacks = 利弊" },
      { word: "feasible",      pos: "adj.",   phonetic: "/ˈfiːzəbl/",      zh: "可行的",         example: "A shorter school day may be feasible in some cities.",         tip: "feasibility (n.) = 可行性" },
      { word: "sustainable",   pos: "adj.",   phonetic: "/səˈsteɪnəbl/",   zh: "可持续的",       example: "A sustainable solution must consider both cost and fairness.",  tip: "sustainable development = 可持续发展" },
      { word: "counterargument",pos: "n.",    phonetic: "/ˈkaʊntərɑːɡjumənt/", zh: "反方论点",  example: "A strong essay should respond to the counterargument.",        tip: "让步反驳段高频" },
      { word: "consensus",     pos: "n.",     phonetic: "/kənˈsensəs/",    zh: "共识",           example: "There is growing consensus that sleep matters for learning.",   tip: "reach a consensus = 达成共识" },
      { word: "implication",   pos: "n.",     phonetic: "/ˌɪmplɪˈkeɪʃən/", zh: "影响；含义",     example: "The finding has important implications for education.",        tip: "implications for = 对……的影响" },
      { word: "root cause",    pos: "phrase", phonetic: "/ruːt kɔːz/",     zh: "根本原因",       example: "The root cause of the problem is unequal access to resources.", tip: "比 cause 更精准" },
      { word: "long-term impact", pos: "phrase", phonetic: "/ˌlɒŋ tɜːm ˈɪmpækt/", zh: "长期影响", example: "The long-term impact of the policy remains unclear.", tip: "影响类作文常用" },
    ],
  },
  {
    id: "writing-practical",
    label: "应用文表达",
    desc: "邀请、建议信、通知与申请",
    icon: "✉️",
    words: [
      { word: "appreciate",    pos: "v.",      phonetic: "/əˈpriːʃieɪt/",  zh: "感激；欣赏",       example: "I would appreciate it if you could reply at your earliest convenience.", tip: "I would appreciate it if... = 礼貌请求" },
      { word: "recommend",     pos: "v.",      phonetic: "/ˌrekəˈmend/",   zh: "推荐；建议",       example: "I strongly recommend this activity to students interested in science.", tip: "recommend doing sth." },
      { word: "inform",        pos: "v.",      phonetic: "/ɪnˈfɔːm/",      zh: "通知；告知",       example: "I am writing to inform you of a change in the schedule.",      tip: "inform sb. of sth." },
      { word: "participate",   pos: "v.",      phonetic: "/pɑːˈtɪsɪpeɪt/", zh: "参加；参与",       example: "All students are encouraged to participate in the volunteer program.", tip: "participate in = 参加" },
      { word: "arrangement",   pos: "n.",      phonetic: "/əˈreɪndʒmənt/", zh: "安排",             example: "The detailed arrangements are listed below.",                 tip: "make arrangements = 做安排" },
      { word: "availability",  pos: "n.",      phonetic: "/əˌveɪləˈbɪləti/", zh: "可用时间；可获得性", example: "Please let me know your availability this Friday.",       tip: "询问时间很自然" },
      { word: "deadline",      pos: "n.",      phonetic: "/ˈdedlaɪn/",     zh: "截止日期",         example: "The deadline for registration is May 20.",                    tip: "meet/miss a deadline" },
      { word: "qualification", pos: "n.",      phonetic: "/ˌkwɒlɪfɪˈkeɪʃən/", zh: "资格；资历",  example: "My previous experience gives me the necessary qualifications.", tip: "申请信常用" },
      { word: "sincerely",     pos: "adv.",    phonetic: "/sɪnˈsɪəli/",    zh: "真诚地",           example: "I sincerely hope you can consider my suggestion.",            tip: "正式语气" },
      { word: "at your convenience", pos: "phrase", phonetic: "/ət jɔː kənˈviːniəns/", zh: "在您方便时", example: "Please contact me at your convenience.", tip: "礼貌表达" },
    ],
  },
  {
    id: "writing-narrative",
    label: "记叙描写词",
    desc: "动作、心理、场景与感悟",
    icon: "🌿",
    words: [
      { word: "glimpse",       pos: "n./v.", phonetic: "/ɡlɪmps/",         zh: "一瞥；瞥见",       example: "I caught a glimpse of my father waiting in the rain.",        tip: "catch a glimpse of = 瞥见" },
      { word: "murmur",        pos: "v./n.", phonetic: "/ˈmɜːmə/",         zh: "低声说；低语",     example: "She murmured a few words of comfort.",                       tip: "动作描写比 say 更细腻" },
      { word: "stare",         pos: "v.",    phonetic: "/steə/",           zh: "凝视；盯着看",     example: "He stared at the letter in disbelief.",                      tip: "stare at = 盯着" },
      { word: "rush",          pos: "v./n.", phonetic: "/rʌʃ/",            zh: "冲；急忙",         example: "A wave of relief rushed through me.",                        tip: "情绪也可以 rush through sb." },
      { word: "overwhelmed",   pos: "adj.",  phonetic: "/ˌəʊvəˈwelmd/",    zh: "不知所措的；深受感动的", example: "I was overwhelmed by their kindness.",              tip: "be overwhelmed by/with" },
      { word: "cherish",       pos: "v.",    phonetic: "/ˈtʃerɪʃ/",        zh: "珍惜",             example: "I will always cherish the memory of that afternoon.",         tip: "cherish a memory/friendship" },
      { word: "realization",   pos: "n.",    phonetic: "/ˌriːəlaɪˈzeɪʃən/", zh: "意识；领悟",    example: "A sudden realization dawned on me.",                         tip: "dawn on sb. = 使某人明白" },
      { word: "silhouette",    pos: "n.",    phonetic: "/ˌsɪluˈet/",       zh: "轮廓；剪影",       example: "His silhouette disappeared into the evening light.",          tip: "场景描写高级词" },
      { word: "warmth",        pos: "n.",    phonetic: "/wɔːmθ/",          zh: "温暖；暖意",       example: "A sense of warmth filled the small room.",                    tip: "可写真实温度或情感" },
      { word: "with a heavy heart", pos: "phrase", phonetic: "/wɪð ə ˈhevi hɑːt/", zh: "心情沉重地", example: "With a heavy heart, she said goodbye.", tip: "结尾告别类场景常用" },
    ],
  },
];

/* ── Synonym data ───────────────────────────────────────────── */
export const READING_SYNONYMS = [
  { base: "important", zh: "重要的",    syns: ["significant", "crucial", "pivotal", "paramount", "vital", "fundamental"] },
  { base: "show",      zh: "表明；显示", syns: ["demonstrate", "illustrate", "suggest", "indicate", "reveal", "manifest"] },
  { base: "think",     zh: "认为；主张", syns: ["argue", "contend", "assert", "maintain", "claim", "posit"] },
  { base: "change",    zh: "改变；影响", syns: ["alter", "transform", "modify", "reshape", "shift", "affect"] },
  { base: "increase",  zh: "增加；上升", syns: ["rise", "surge", "escalate", "amplify", "expand", "soar"] },
  { base: "decrease",  zh: "减少；下降", syns: ["decline", "diminish", "alleviate", "mitigate", "curtail", "shrink"] },
  { base: "cause",     zh: "导致；引起", syns: ["result in", "give rise to", "engender", "precipitate", "trigger"] },
  { base: "difficult", zh: "困难的",    syns: ["challenging", "intricate", "complex", "sophisticated", "arduous"] },
  { base: "obvious",   zh: "明显的",    syns: ["apparent", "evident", "manifest", "discernible", "conspicuous"] },
  { base: "people",    zh: "人们",      syns: ["individuals", "citizens", "the public", "stakeholders", "one"] },
  { base: "main",      zh: "主要的",    syns: ["primary", "central", "principal", "dominant", "major", "core"] },
  { base: "result",    zh: "结果",      syns: ["consequence", "outcome", "effect", "implication", "aftermath", "finding"] },
  { base: "method",    zh: "方法",      syns: ["approach", "strategy", "technique", "procedure", "means", "practice"] },
  { base: "explain",   zh: "解释",      syns: ["account for", "clarify", "interpret", "illustrate", "make sense of", "expound"] },
  { base: "support",   zh: "支持",      syns: ["back up", "substantiate", "justify", "reinforce", "bolster", "corroborate"] },
  { base: "different", zh: "不同的",    syns: ["distinct", "diverse", "varied", "separate", "contrasting", "alternative"] },
  { base: "possible",  zh: "可能的",    syns: ["plausible", "potential", "likely", "probable", "conceivable", "feasible"] },
  { base: "unclear",   zh: "不清楚的",  syns: ["ambiguous", "vague", "uncertain", "obscure", "implicit", "open-ended"] },
];

export const WRITING_SYNONYMS = [
  { base: "in conclusion", zh: "总而言之",  syns: ["to summarize", "in sum", "overall", "ultimately", "all in all"] },
  { base: "furthermore",   zh: "此外；而且", syns: ["moreover", "additionally", "in addition", "besides", "what's more"] },
  { base: "however",       zh: "然而",      syns: ["nevertheless", "nonetheless", "yet", "on the other hand", "conversely"] },
  { base: "because",       zh: "因为",      syns: ["due to", "owing to", "as a result of", "on account of", "given that"] },
  { base: "for example",   zh: "例如",      syns: ["for instance", "such as", "to illustrate", "namely", "specifically"] },
  { base: "very / quite",  zh: "非常；相当", syns: ["remarkably", "exceptionally", "particularly", "notably", "considerably"] },
  { base: "big / large",   zh: "大的",      syns: ["substantial", "considerable", "extensive", "significant", "immense"] },
  { base: "good",          zh: "好的；积极", syns: ["beneficial", "advantageous", "favorable", "constructive", "desirable"] },
  { base: "show / prove",  zh: "展示；证明", syns: ["demonstrate", "substantiate", "illustrate", "exemplify", "validate"] },
  { base: "problem",       zh: "问题",      syns: ["challenge", "issue", "concern", "predicament", "dilemma"] },
  { base: "help",          zh: "帮助；促进", syns: ["facilitate", "enable", "assist", "contribute to", "promote", "support"] },
  { base: "harm",          zh: "损害；危害", syns: ["undermine", "impair", "damage", "jeopardize", "pose a threat to", "have a negative impact on"] },
  { base: "solve",         zh: "解决",      syns: ["address", "tackle", "resolve", "deal with", "cope with", "work out"] },
  { base: "use",           zh: "使用；利用", syns: ["utilize", "employ", "make use of", "apply", "adopt", "harness"] },
  { base: "need",          zh: "需要",      syns: ["require", "call for", "necessitate", "demand", "be in need of", "depend on"] },
  { base: "important thing", zh: "重要事情", syns: ["priority", "key factor", "central concern", "core issue", "essential element", "major consideration"] },
  { base: "more and more", zh: "越来越多",  syns: ["increasingly", "a growing number of", "an increasing amount of", "on the rise", "ever more", "steadily growing"] },
  { base: "I think",       zh: "我认为",    syns: ["I believe", "I would argue that", "from my perspective", "it seems to me that", "I am convinced that", "my view is that"] },
];
