export const TEACHER_MODULES = [
  {
    id: "writing",
    label: "写作",
    desc: "作文 · 批改 · 实战",
    accent: "#a0522d",
    soft: "#eadbd4",
    workbenchPage: "assignment-create",
    prepPage: "writing",
  },
  {
    id: "grammar",
    label: "语法",
    desc: "分析 · 练习 · 精讲",
    accent: "#5548a8",
    soft: "#ded9ef",
    workbenchPage: "grammar-workbench",
    prepPage: "grammar-analyzer",
  },
  {
    id: "reading",
    label: "阅读",
    desc: "思维 · 练习 · 精读",
    accent: "#1f7a5c",
    soft: "#d9e8e3",
    workbenchPage: "reading-workbench",
    prepPage: "reading-analyzer",
  },
  {
    id: "vocab",
    label: "词汇",
    desc: "分析 · 检测 · 精讲",
    accent: "#1a5fa8",
    soft: "#d7e2ee",
    workbenchPage: "vocab-workbench",
    prepPage: "vocab-analyzer",
  },
  {
    id: "listening",
    label: "听读",
    desc: "辨音 · 精听 · 模拟",
    accent: "#8a6800",
    soft: "#e9e4d6",
    workbenchPage: "listening-workbench",
    prepPage: "listening-basics",
  },
  {
    id: "phonetics",
    label: "语音",
    desc: "音素 · 拼读 · 句子",
    accent: "#a0307a",
    soft: "#ecd8e5",
    workbenchPage: "phonetics-workbench",
    prepPage: "phonetics-overview",
  },
  {
    id: "speaking",
    label: "口语",
    desc: "实时 ASR · 表达反馈",
    accent: "#2f6f8f",
    soft: "#d7e6ec",
    workbenchPage: "speaking-workbench",
    prepPage: "speaking",
  },
];

export const TEACHER_PREP_TABS = [
  { label: "写作", page: "writing" },
  { label: "语法", page: "grammar-analyzer" },
  { label: "阅读", page: "reading-analyzer" },
  { label: "词汇", page: "vocab-analyzer" },
  { label: "听读", page: "listening-basics" },
  { label: "语音", page: "phonetics-overview" },
  { label: "口语", page: "speaking" },
];
