export const QUESTION_ANALYSIS_RECOVERY_INTERVAL_MS = 60 * 1000;
export const QUESTION_ANALYSIS_STALE_MS = 5 * 60 * 1000;
export const QUESTION_ANALYSIS_STARTUP_RECOVERY_DELAY_MS = 1500;
export const QUESTION_ANALYSIS_HEARTBEAT_INTERVAL_MS = 5000;
export const QUESTION_ANALYSIS_MAX_ATTEMPTS = 4;
export const QUESTION_ANALYSIS_RETRY_BASE_MS = 4000;
export const QUESTION_ANALYSIS_WORKER_ID = `question-analysis-worker:${process.pid}`;
