export default {
  type: 'continuation',
  label: '读后续写',
  icon: '📖',
  color: '#f59e0b',
  requiredFields: [
    'storyLine.who',
    'storyLine.when',
    'storyLine.where',
    'storyLine.why',
    'storyLine.what',
    'storyLine.result',
    'emotionLine.initial',
    'emotionLine.changes',
    'emotionLine.tone',
    'plotAnalysis.originalText',
    'plotAnalysis.translation',
    'plotAnalysis.keyLines',
    'starters.para1.text',
    'starters.para1.translation',
    'starters.para1.constraints',
    'starters.para1.directions',
    'starters.para1.forbidden',
    'starters.para2.text',
    'starters.para2.translation',
    'starters.para2.constraints',
    'starters.para2.directions',
    'starters.para2.forbidden',
    'starters.relationship',
    'contentAnalysis.plotLogic.accuracy',
    'contentAnalysis.plotLogic.coherence',
    'contentAnalysis.plotLogic.closure',
    'contentAnalysis.plotLogic.score',
    'contentAnalysis.characterConsistency.motivation',
    'contentAnalysis.characterConsistency.emotion',
    'contentAnalysis.characterConsistency.score',
    'contentAnalysis.themeAlignment.comment',
    'contentAnalysis.themeAlignment.score',
  ],
};